### ISSUE TITLE
Rfam_for_miRdeep.fa

### ISSUE THREAD

**Issue by dnething89** [rajewsky-lab/mirdeep2#1]
I'm Running miRDeep2 v2.0.0.8 on Linux Mint 18.1, fresh install. installed miRDeep2 and dependencies via Bioconda.

I'm trying to get miRDeep2 running, and the error "Rfam_for_miRDeep.fa not found in your miRDeep2 scripts directory" kept popping up. The file Rfam_for_miRDeep.fa was in the /bin directory along with miRDeep2.pl, but it didn't work. Just through an accident, I placed the Rfam_for_miRDeep.fa file in the directory above the /bin, and that error stopped occurring. Is that expected behavior? I kept getting the same error on a fresh Ubuntu install as well, but I have not confirmed the fix there.

Thanks

**Comment by Drmirdeep** [comment]
Hi Dan,

we don't provide the Bioconda package so we cannot do anyhting about it.
However, in the github version this error is not present.

Best regards,
Sebastian

--
Sebastian Mackowiak, Ph.D.
Friedländer Lab, Computational RNA Biology
The Wenner-Gren Institute, MBW

Science for Life Laboratory
Karolinska Institutet Science Park
Tomtebodavägen 23A
171 65 Solna
Sweden

**Comment by caot** [comment]
miRDeep2.pl has the following code, so it's right to place or link the Rfam_for_miRDeep.fa file in the directory above the bin
`${scripts}/../Rfam_for_miRDeep.fa`
