### ISSUE TITLE
Negative repeat count does nothing at /home/bioSoft/mirdeep2/bin/miRDeep2_core_algorithm.pl line 1492

### ISSUE THREAD

**Issue by wangzhennan14** [rajewsky-lab/mirdeep2#10]
Hi, 
     When I run mirDeep2  with example data, there was some errors, and I do not know what's the matter about these problems.
     
![screenshot](https://user-images.githubusercontent.com/17285718/41777818-3f93d722-765f-11e8-9f57-b574f9ace6f8.png)
![screenshot_1](https://user-images.githubusercontent.com/17285718/41777896-820f11b6-765f-11e8-9e5b-86ab02d03970.png)
![screenshot_2](https://user-images.githubusercontent.com/17285718/41777898-82571b82-765f-11e8-93e7-9d018e2fe48f.png)
![screenshot_3](https://user-images.githubusercontent.com/17285718/41777899-829257ba-765f-11e8-822f-060aa76b2fb7.png)
![screenshot_4](https://user-images.githubusercontent.com/17285718/41777902-82dce726-765f-11e8-8c6d-6da3582a7a61.png)
![screenshot_5](https://user-images.githubusercontent.com/17285718/41777904-832be736-765f-11e8-93c6-b6041ba30ad0.png)
      I installed mirDeep2 follow the INSTALL, and I use the git version. What was the matter? Please give me some advice to solve this problems! Thank you very much!
                                                                                                             Wang

**Comment by mschilli87** [comment]
@wangzhennan14: It would be *much* easier to troubleshoot your problem if you would copy/paste the *text* input/output as *text*: This allows to delete unimportant bits, copy/pasting your exact commands to try them out and is just more readable than going throw a set of screenshots.

**Comment by Drmirdeep** [comment]
Please run perl install.pl and the mirdeep2 directory  
and post the output here. If everything is successfully installed there should be no such error.

**Comment by Drmirdeep** [comment]
I put a workaround in the file miRDeep2.pl so the error message should not occur anymore.

**Comment by kisun** [comment]
Hi, I also have this problem but in line 1345. One of such lines is below:

`Negative repeat count does nothing at /wrk/kipokh/DONOTREMOVE/bioconda_env/mytools/bin/miRDeep2_core_algorithm.pl line 1345, <FILENAME> line 2508317.`

could you please look into it? thanks! Kisun

**Comment by Drmirdeep** [comment]
@kisun
This is likely dependent on your Perl version/environment used. As the warning implies it does nothing. The whole lines try to make a uniform output format but does not interfere with any calculations.
Anyhow, please do another checkout of the repository and see if the warning still pops up.

**Comment by mschilli87** [comment]
@kisun: This should be resolved with the [new release](https://github.com/rajewsky-lab/mirdeep2/releases/tag/v0.1.1).
Please open a new issue with all necessary details in case you still experience any problems.

**Comment by erickfabian0** [comment]
Hi @Drmirdeep , I also have this problem but in different line, and whit quantifier.pl in line 1312. One of such lines is below:
negative repeat count does nothing at quantifier.pl line 1312, <in> line 5603.



Line 1312 of my miRDeep2_core_algorithm is:
my $mat = $hash{$k1}{$k2}{'mature'};;

could you please look into it? thanks!

**Comment by mschilli87** [comment]
@erickfabian0: See https://github.com/rajewsky-lab/mirdeep2/issues/26#issuecomment-2307653700.
