### ISSUE TITLE
Whitespaces not allowed

### ISSUE THREAD

**Issue by DylanDSouzaInd** [rajewsky-lab/mirdeep2#107]
#Starting miRDeep2
/home/rajesh/mirdeep2/bin/miRDeep2.pl merged.fa ../../03_db/chrygca710275/penref.fasta rnareads_vs_genome.arf none none none

miRDeep2 started at 14:3:22

mkdir mirdeep_runs/run_30_11_2022_t_14_03_22

[1;31mError: [0mGenome file ../../03_db/chrygca710275/penref.fasta has not allowed whitespaces in its first identifier

Hi how do I overcome this from my reference genome for penicillium.

**Comment by mschilli87** [comment]
Just change the FASTA file before running miRDeep2.
