### ISSUE TITLE
bowtie issues when installing mirdeep2

### ISSUE THREAD

**Issue by mukiibi** [rajewsky-lab/mirdeep2#11]
Hi,
I kindly need some help about installing mirdeep2 on my ubuntu running system.
I ran the install.pl script and I got the following error.

**Building of /home/robert/programs/mirdeep2_0_0_8/essentials/bowtie-1.2.2/bowtie not successful
Please have a look at the install.log and install_error.log in 
        the essentials directory
         at ./install.pl line 766.**
I tried downloading bowtie manually by myself and ran the script again bu the same error appears....when i look into the log file for the error message i do not see anything written in the file.
I would greatly appreciate any help to go about this.
Thank you in advance
Robert

**Comment by Drmirdeep** [comment]
Hi Robert, 

please remove the directory essentials/bowtie-1.2.2/

and run the install.pl script again. The script itself does not (at least the current version in the git-hub) download bowtie versions above 1.1.1. So where ever it came from please delete it.

Let us know if that worked.

**Comment by mukiibi** [comment]
Thank you Marcel, I have installed the copy of mirDeep2 from git-hub (src).
It worked perfect.
Thank you,
Robert
