### ISSUE TITLE
mapper.pl takes a long time for some data

### ISSUE THREAD

**Issue by Chenmi0820** [rajewsky-lab/mirdeep2#110]
Hello everyone,

I have some data of samples for mapple.pl analysis. At the beginning it was smooth, with each sample taking about 10 minutes to generate the .arf file. However, for some samples which are more than 25 million but less than 30 million, it has been running for 3 days with no results but the temporary file could be generated.

Given that some samples can run properly, I think the command is fine. 
**mapper.pl /depot/leizhang/data/name.fa -c -j -l 18 -m -p /depot/leizhang/data/meloidogyne_incognita.PRJEB8714.WBPS17.genomic -s name_collapsed.fa -t name_collapsed_vs_genome.arf**

Any advice for this situation? Thanks!

**Comment by Drmirdeep** [comment]
Sounds like a memory issue but you will have to do some debugging. Maybe split the problematic file into half’s and run them separately

**Comment by Chenmi0820** [comment]
It's actually a memory issue. Thank you!
