### ISSUE TITLE
One precursor have two locations of mature miRNA sequence

### ISSUE THREAD

**Issue by Yuzhang0102** [rajewsky-lab/mirdeep2#111]
Hi, 
I firstly merged and collapsed my all fastq data of all samples to predict novel miRNAs by miRDeep2.pl. Then I used the output precursor and mature fasta to run quantifier.pl for each sample. But I got two reads counts of some miRNA in the results.
`quantifier.pl -p novel_pres_07_04_2023_t_15_26_33_score-50_to_na.fa -m novel_mature_07_04_2023_t_15_26_33_score-50_to_na.fa -r sample1.fa -d`
 I checked  these miRNAs found that the precursor have two locations of mature miRNA sequence, like this:
![image](https://user-images.githubusercontent.com/90377984/234806327-85c14cd0-cc2f-46cd-83d7-cf9ebeda851a.png)
But the mature miRNA structure is this:
![image](https://user-images.githubusercontent.com/90377984/234806606-1068efbd-d3e0-4104-a405-2953444a408a.png)
So my questions are
1. Do quantifier.pl and miRDeep2.ple have different mapping strategy? The reads mapping to the precursor are unique mapped, for quantifier.pl how to decide the read map to which location?
2. The second mature miRNA is the miRNA predicted by mirdeep2.pl, but its counts are less than the first miRNA, why?
3. Can this sRNA still be a positive miRNA?

**Comment by mschilli87** [comment]
IIRC, `miRDeep2.pl` calls (potentially novel) miRNA(-precursor)s from reads mapped to the genome, whereas `quantifier.pl` maps reads to (annotated) miRNAs (trading specificity for sensitivity). I hope this answers your first question. Regarding your second and third question, I am not sure I get what you are asking. Maybe @Drmirdeep can provide a better answer.

**Comment by Yuzhang0102** [comment]
Thanks for your replies!
I have looked at the options of quantifier.pl many times, but I don't know how to avoid this condition, or it can't be avoid?
