### ISSUE TITLE
unable to extract files from mirbase using  extract_miRNAs.pl ~/mirbase/21/mature.fa.gz hsa > mature_ref.fa

### ISSUE THREAD

**Issue by varshinivempadapu** [rajewsky-lab/mirdeep2#112]
ive been trying to download files from mirbase using mirbase.pl-- the file created but is empty.  Also any further extract commands are showing --- extract_miRNAs command not found. Please help

**Comment by Drmirdeep** [comment]
there is no mirbase.pl in this repo
