### ISSUE TITLE
[FR] support using Perl versions installed elsewhere but `/usr/bin/perl`

### ISSUE THREAD

**Issue by albenstein** [rajewsky-lab/mirdeep2#113]
We are using mirdeep2 on our HPC system. When we try to call mirdeep2.pl, it gives this error:

`Perl v5.35.7 required--this is only v5.26.3, stopped at /opt/ohpc/pub/compiler/perl/5.36.0/lib/5.36.0/File/Copy.pm line 10.`
`BEGIN failed--compilation aborted at /opt/ohpc/pub/compiler/perl/5.36.0/lib/5.36.0/File/Copy.pm line 10.`
`Compilation failed in require at /opt/ohpc/pub/apps/mirdeep2/0.1.3/bin/miRDeep2.pl line 25.`
`BEGIN failed--compilation aborted at /opt/ohpc/pub/apps/mirdeep2/0.1.3/bin/miRDeep2.pl line 25.`

Could you please help on this issue?

**Comment by albenstein** [comment]
miRDeep2.pl using perl 5.36.0.

**Comment by albenstein** [comment]
`$ perl --version

This is perl 5, version 36, subversion 0 (v5.36.0) built for x86_64-linux`

**Comment by mschilli87** [comment]
@albenstein:
> miRDeep2.pl using perl 5.36.0.

I see... 🤔 
How exactly did you install miRDeep2?

**Comment by albenstein** [comment]
We installed miRDeep2 with manual installation which is written on README.md

**Comment by mschilli87** [comment]
@albenstein:
> We installed miRDeep2 with manual installation which is written on README.md

Thank you for following up and providing the necessary information.
I'll have to hand over to @Drmirdeep regarding a possible solution though.

**Comment by Drmirdeep** [comment]
Seems to be related to the copy.pm module. I cannot help with it. This is related to the Perl installation you have on your machines.

**Comment by albenstein** [comment]
On perl e-mail group they said this:
`So, are you using the correct path for the latest version of perl?
It seems you have the right perl and File::Copy installed, but your program is using the old version.`
How can we see miRDeep.pl uses which version of perl?

**Comment by albenstein** [comment]
I figured out the problem. On mirdeep2 program there is a line at the begining calls perl. I changed this line with perl5.36.1 with absolute path. Program starts to run.
Thanks for help

**Comment by mschilli87** [comment]
@albenstein: Are you referring to the `#!/usr/bin/perl` line? If so, you should be able to override it without the need to modify `miRDeep2.pl` by calling `perl5.36.1 $(which miRDeep2.pl)` instead of `miRDeep2.pl`.

---
@Drmirdeep: We could consider replacing the `#!/usr/bin/perl` shebang by `#!/usr/bin/env perl` to always use the same `perl` binary as running `perl` from the shell would. Any thoughts?

**Comment by albenstein** [comment]
I've just changed shebang with `#!/usr/bin/env perl` . Program runs again.

**Comment by albenstein** [comment]
mapper.pl has same issue. After I've changed shebang, it started to run.

**Comment by Drmirdeep** [comment]
Seems to be an edge case. 🤷🏼‍♂️ a simple patch to the installed files will work.

**Comment by mschilli87** [comment]
I wouldn't consider every Perl install outside of `/usr/bin` 'faulty' but as I said: Your call. 🤷
