### ISSUE TITLE
minimum score cut-off (-b) with -10 gives fewer results than with -5

### ISSUE THREAD

**Issue by jontejj** [rajewsky-lab/mirdeep2#117]
I used -b -10 as parameter to miRDeep2.pl and it gave me only one novel miRNA:s, when I used -b -5 I got a lot more? I thought I would get a lot more results with -b -10?
![b-10](https://github.com/rajewsky-lab/mirdeep2/assets/1108726/e23ca52a-b264-4ce7-995d-9952837c8593)
![b-5](https://github.com/rajewsky-lab/mirdeep2/assets/1108726/7e64518a-e462-46dc-a178-6eba071e2355)

**Comment by Drmirdeep** [comment]
:-) Seems like a string vs number comparison operator error.
