### ISSUE TITLE
RNAfold throws error caused by a typo

### ISSUE THREAD

**Issue by tinavisnovska** [rajewsky-lab/mirdeep2#12]
file: mirdeep2/src/miRDeep2.pl
line: 716
a dash missing in --noPS option is causing RNAfold error about invalid option -- n.

**Comment by mschilli87** [comment]
@tinavisnovska: Looking at the context of this line, this seems to be intended.
After trying with `-noPS`, miRDeep2 tries again with `--noPS` if the first attempt failed:

https://github.com/rajewsky-lab/mirdeep2/blob/5d6c428fe7b8e6e6d008b9feb2e7791db734d5e0/src/miRDeep2.pl#L716-L718

So my guess is differen versions of RNAfold behave differently and this is working around that issue.

---
@Drmirdeep: Maybe adding a comment would help here? :wink:

**Comment by Drmirdeep** [comment]
Everything is working as intended. Of course a little hint that this is just a verbose message would maybe be helpful.

**Comment by tinavisnovska** [comment]
@Drmirdeep: ah, now I see,... however, with this code, I end up with an error message from a command that was not even executed in my run of miRDeep2.pl, which is a bit confusing.

**Comment by tinavisnovska** [comment]
@Drmirdeep: maybe distinguishing between the two RNAfold command forms (if that does not depend only on RNAfold version) with a test like `RNAfold -h | grep -c "^\s*\-\-noPS"` 
could be a better way to decide which command form to run even before actually running RNAfold.
