### ISSUE TITLE
miRDeep2.pl running slow

### ISSUE THREAD

**Issue by dhananyashunmugam** [rajewsky-lab/mirdeep2#122]
I'm using mirDeep2.pl for quantification of miRNA. My mirdeep2 mapping (mapper.pl) .arf, .fasta file is around 50 to 60mb . My system has 56gb ram and Im using all 12 threads. But for 1 sample its taking 4hrs time. Is there any option to speed up the process?

**Comment by mschilli87** [comment]
Without any additional information about your data and command, nobody will be able to help. Also, if there was a general way to magically 'make it faster' that would be the default and nor reserved for poeple who ask on Github. So I doubt that there is much anybody could do to help you even if we had more information. Try running the tutorial. If that is slow, it's your setup. If that's fast, it's something about your data or the way you run miRDeep2 and beyond the support we can offer for free in our spare time.
