### ISSUE TITLE
How to generate count matirx when the type of mature miRNA is the same but the precursor miRNA is different

### ISSUE THREAD

**Issue by g0656116** [rajewsky-lab/mirdeep2#124]
Using mirdeep2, we obtained the “miRNAs_expressed_all_samples_22_02_2024_t_08_01_36.csv” file.
Although it was convenient to have normalization values ​​here, there were many duplicated mature and precursor miRNA values. 
So, I googled and found a post by a user who said that only the maximum value among the raw read counts of duplicated mature miRNAs was selected and used.

During this process, several questions arose.

1.Can I just select and use the maximum value like in that post?
So is there any chance of it affecting total read counts or anything else?
2.  If only the maximum value is selected and used, does the normseq value provided by mirdeep2 have to be modified?
3. And how mirdeep2 becomes a mature miRNA
Distinguish between precursor and precursor? Or vice versa, distinguish mature miRNA from precursor?
4. I am planning to analyze using DESeq2. Is there any other work required other than removing duplicate mature miRNAs?

This is my first time analyzing miRNAs, so I'm sorry if I'm asking too many rudimentary questions.
Thanks for your help.

**Comment by Drmirdeep** [comment]
Maybe have a look at the quantifier.pl. There are some options you can use.
