### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by yefanglee** [rajewsky-lab/mirdeep2#125]
Hi, I met an issue when I installed package. I run the code _perl install.pl_, but when installed ViennaRNA-1.8.4, errors were as follows:
```
make: *** [Makefile:239: all] Error 2
/usr/bin/ld: ../lib/libRNA.a(libRNA_a-subopt.o):(.bss+0xfa8): multiple definition of `Fc'; ../lib/libRNA.a(libRNA_a-fold.o):(.bss+0x10): first defined here
/usr/bin/ld: ../lib/libRNA.a(libRNA_a-subopt.o):(.bss+0xfac): multiple definition of `FcH'; ../lib/libRNA.a(libRNA_a-fold.o):(.bss+0x14): first defined here
/usr/bin/ld: ../lib/libRNA.a(libRNA_a-subopt.o):(.bss+0xfb0): multiple definition of `FcI'; ../lib/libRNA.a(libRNA_a-fold.o):(.bss+0x18): first defined here
/usr/bin/ld: ../lib/libRNA.a(libRNA_a-subopt.o):(.bss+0xfb4): multiple definition of `FcM'; ../lib/libRNA.a(libRNA_a-fold.o):(.bss+0x1c): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:355: RNAsubopt] Error 1
make: *** [Makefile:323: install-recursive] Error 1
```
Can anyone give me some suggestion to solve it? Thank you!

**Comment by mschilli87** [comment]
@yefanglee: How are you trying to install miRDeep2? Which version are you trying to install? On what operating sytem are you? Where did you download miRDeep2 from? What commands have been running to install miRDeep2 that made you run into this error?

**Comment by yefanglee** [comment]
> @yefanglee: How are you trying to install miRDeep2? Which version are you trying to install? On what operating sytem are you? Where did you download miRDeep2 from? What commands have been running to install miRDeep2 that made you run into this error?

Thanks for your reply. I tried to install miRDeep2 v0.1.3 downloaded from github. And the ViennaRNA v1.8.4 was downloaded automatically but it showed that RNAfold was not installed successfully. My operating system is Rocky Linux 9.2 and gcc version is 11.3.1. I run the code `source ~/.bashrc`, followed by `perl install.pl`, and then this error was written in install_error.log.

**Comment by mschilli87** [comment]
@yefanglee: Thank you for providing the information.

---
@Drmirdeep: Any idea? I could try a fresh install on the weekend if that helps.

**Comment by Drmirdeep** [comment]
I am getting actually different compiler errors for RNAfold. Seems like something has changed

**Comment by Drmirdeep** [comment]
As a current workaround please try to install the latest ViennaRNA package manually

**Comment by Drmirdeep** [comment]
Great. I also did a bit of debugging on the ViennaRNA code. 

I could get rid of the errors by deleting the files 
libRNA_a-subopt.o
libRNA_a-fold.o
in ViennaRNA-1.8.4/lib

and just reran 
make
