### ISSUE TITLE
UMI data

### ISSUE THREAD

**Issue by denise0593** [rajewsky-lab/mirdeep2#128]
Dear,
I'm using mirdeep2 on my sequencing data, I would like to know if you can suggest me how to deal with data with QIAGEN UMI, because when mirdeep2 collapsed reads does not consider UMI. Do you have any suggestion?
Thanks a lot

**Comment by mschilli87** [comment]
You can pre-process the reads with adapter trimming tools (or custom scripts) before passing them to miRDeep.

**Comment by denise0593** [comment]
Yes, I've done that with umitools, but after when I use mirdeep2 the information given by UMI will be lost...

**Comment by mschilli87** [comment]
What information are you referring to? The actual UMI sequence? I don't see why this would be required for / downstream of miRDeep2: UMIs are typically used to distinguish indendent reverse-transcription events from PCR duplicates (and in the case of adapter ligation, to reduce ligation biases). Both can be achieved with the following pre-processing:

1. Collapse identical (incl. UMIs) reads.
2. Trim UMIs.
3. Run miRDeep2.

Step 1 ensures that miRDeep2 only gets to see (and thus count) one read for each UMI. Thus, PCR duplicates won't be double-counted.
Step 2 avoids the UMI sequences interfering with the mapping itself and allows miRDeep2 to count the same read sequence (excl. UMIs) multiple times, as long as the (now trimmed) UMI used to be different. Thus, multiple independent copies of the same read reverse-transcribed independently from different transcripts of the same miRNA are not overcollapsed.

The fact that miRDeep2 itself collapses identical reads is an implementation detail that allows it to process typical sRNA-seq data (with many copies of the same few miRNAs, depending on the tissue) much faster by mapping each distinct sequence only once to the genome / miRNA reference. It does so keeping track of the read multiplicities and properly considers those for quantification purposes. Note that this is completely independent from the collapsing of PCR-duplicates using UMIs discussed above though.

AFAIK, miRDeep2 doesn't (and won't) support these pre-processing steps directly without the need for manual pre-processing though. @Drmirdeep: Please correct me if I am wrong about this.
