### ISSUE TITLE
make_html.pl: lines 2680 - 2694.

### ISSUE THREAD

**Issue by tinavisnovska** [rajewsky-lab/mirdeep2#13]
Hi, I am getting error messages saying

> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/option{ <-- HERE t}\s*=\s*(\S+)/ at /Users/tina/anaconda2/envs/mirdeep2/bin/make_html.pl" on lines 2680, 2683, 2686, 2689, 2692, and 2694.

I suspect that line 

```perl
}elsif(/option{t}\s*=\s*(\S+)/){
```

should be changed to 

```perl
}elsif(/\Q$options{'t'}\E\s*=\s*(\S+)/){
```

and all the other mentioned lines edited accordingly.

**Comment by mschilli87** [comment]
@tinavisnovska:

1. Which version of miRDeep2 are you runnning?
2. How did you install miRDeep2?
3. Can you reproduce this error with the example/test data provided by miRDeep2?
4. If not, can you share a *minimal* example with copy/paste-able code and the corresponding (minimal!) input data?

**Comment by Drmirdeep** [comment]
As the warning message indicates this is not a BUG. It clearly states(Unescaped left brace in regex is deprecated) that this is perl version specific so you can just ignore it.

**Comment by tinavisnovska** [comment]
1) version 2.0.0.8
2) bioconda
3) didn't try yet, will look at this and comment on this later
4) I don't think this is an option

**Comment by Drmirdeep** [comment]
You can of course just escape the { with \ if the warnings are disturbing.

**Comment by tinavisnovska** [comment]
@Drmirdeep: in the whole script, hash called 'options' is used except for these 6 lines, where name 'option' (s is missing at the end) is used without dollar sign, so that the variable value is not even used inside the Regexes . But yes, this is very likely only perl version specific that can be ignored...

**Comment by Drmirdeep** [comment]
Please look closer into the source code before posting these things here since they are not related to each other. Thanks.

**Comment by tinavisnovska** [comment]
if you are keen to follow the next example, I'll show you that the two are related:

1. let's have the text.txt file containing two lines: 
option1 = value1
option2 = value2

2. let's have a short perl script test.pl with this code:
use strict;
use Data::Dumper;

my %options;
$options{'x'}="option1";
$options{'y'}="option2";

print Dumper(\%options);

open FH,"<test.txt" or die;

while(<FH>){
        if (/option{x}\s+=\s+(\S+)/){
                print $1,"\n";
                next;
        }
}

this code contains the same problem as the make_html.pl file. if this generates the message about the left brace in regex for you, what happens if you change the line with if-condition to "if (/\Q$options{'x'}\E\s+=\s+(\S+)/){" ?

Yes, I played with the code already before rising the issue at all and as I said, I suspect that the problem is exactly where I said.

**Comment by tinavisnovska** [comment]
Thanks for your time and for explaining. 

What I still can't get is, when when the options option{t}, option{q}, ..., option{v} occur in the parameters file. Any comment on that would be helpful and appreciated. 
Cheers.

**Comment by tinavisnovska** [comment]
got it, finally.
