### ISSUE TITLE
No file precursors.fa_stack found

### ISSUE THREAD

**Issue by huangziyan11111** [rajewsky-lab/mirdeep2#17]
Hi,
I met a problem. I wanted to use mirdeep2 to find the new miRNA, the data is of rice species. When I use `miRDeep.pl`, this error appeared:

```
41      66600
42      65026
43      63654
44      62300
45      60926
46      59812
47      58674
48      57480
49      56400
No file mirdeep_runs/run_26_10_2018_t_10_49_21/tmp/precursors.fa_stack found
```

So I checked the `excise_precursors_iterative_final.pl` and found I can increase the value of `upper_bound` or increase the value of `pres_max` to solve this bug. I tried to increase `upper_bound` from `50` to `70`, and got `precursors.fa_stack` file which contained `56`. But I don't know the meaning of the two parameter. Could you help me to fix it? Thank you.

---
*edited by @mschilli87: fixed formatting*

**Comment by mschilli87** [comment]
@huangziyan11111: 
The `pres_max` parameter for `excise_precursors_iterative_final.pl` is passed down from `miRDeep2.pl`s `-g <int>` command line option which is documented as follows:

> maximum number of precursors to analyze when automatic excision gearing is used.  
> default=50.000, if set to -1 all precursors will be analyzed

Have you tried running `mirRDeep2.pl` with `-g 1`?

I guess it is possible that the default miRDeep2 parameters don't work well for the rice genome.
Do you get reasonable results after increasing `upper_bound`?

---
@Drmirdeep:
Any pointers on why `upper_bound` was hardcoded to 50?

**Comment by mschilli87** [comment]
@huangziyan11111: Is this still an issue for you?

**Comment by Drmirdeep** [comment]
50 was hardcoded back in the days since the number of precursors after this many repetitions was always below 50,000. Apparently you have hit a case where this is violated ...

**Comment by mschilli87** [comment]
Closing this as 'wontfix' as it seems to be an edge case with a known workaround. Feel free to re-open as a feature request to increase the upper bound or make it configurable via a command line flag.
