### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by gkare** [rajewsky-lab/mirdeep2#19]
mirdeep2 version 8: getting this error:

```
Building of /Users/sysadmin/desktop/mirdeep2_0_0_8/essentials/bowtie-1.2.2/bowtie not successful 
Please have a look at the install.log and install_error.log in the essentials directory at install.pl line 766.
```

---
*edited by @mschilli87: copied/formatted issue text from issue title.*

**Comment by mschilli87** [comment]
@gkare:

1. There is no 'version 8'. I assume you are referring to [miRDeep2 v. 0.0.8](https://github.com/rajewsky-lab/mirdeep2/releases/tag/v0.0.8).
Could you please try the [latest version](https://github.com/rajewsky-lab/mirdeep2/releases/latest) before opening an issue? Maybe you hit a bug that was fixed already.

2. Before asking for help, could you please try to solve the problem yourself by reading the error message and trying what it suggests?

3. If the log is not helpful to you you please share it here. Without any information nobody will be able to help you.  ["Doesn't work" doesn't work!](https://www.macieira.org/blog/2012/05/doesnt-work-doesnt-work/) :wink:

4. If you want people to make an effort to help you, please make an effort to help them help you: Please describe in detail what you did and use proper formatting for code and output.

**Comment by gkare** [comment]
I am using the latest version, which is mirdeep2_0_0_8 (downloaded from https://www.mdc-berlin.de/n-rajewsky#t-data,software&resources) on macOS Mojave on terminal.
On the terminal: mirdeep2_0_0_8 sysadmin$ I typed perl install.pl. I get this message :
---------------------------------
Installing bowtie binaries

Building of /Users/sysadmin/desktop/mirdeep2_0_0_8/essentials/bowtie-1.2.2/bowtie not successful
Please have a look at the install.log and install_error.log in 
		the essentials directory
		 at install.pl line 766.
-----------------------------
I look in install error log file- it is blank.
I look in install log file- the last line is: Archive:  bowtie-1.2.2-macos-x86_64.zip

**Comment by mschilli87** [comment]
@gkare:

1. The latest [miRDeep2 v. 0.1.0 version is](https://github.com/rajewsky-lab/mirdeep2/releases/tag/v0.1.0) and I linked it in my previous post. Please carefully read responses you get before replying.

2. If you can reproduce the error with the latest version, please share the *full* log, not just the last line. :wink:

---
@sztankatt: We should update the Rajewsky lab page to either include all releases (ideal solution) ot at least point to https://github.com/rajewsky-lab/mirdeep2/releases for new releases. Could you please take care of this?

@Drmirdeep: Assuming this can be reproduced with the latest version - any idea what is going wrong based on the information available?

**Comment by gkare** [comment]
the new version worked. I also tested on tutorial dir, it worked. thanks
