### ISSUE TITLE
Update Rajewsky lab web page

### ISSUE THREAD

**Issue by mschilli87** [rajewsky-lab/mirdeep2#20]
Do avoid further issues like https://github.com/rajewsky-lab/mirdeep2/issues/19, we should update the [Rajewsky lab web page](https://www.mdc-berlin.de/n-rajewsky#t-data,software&resources) to either include all releases (ideal solution) ot at least point to https://github.com/rajewsky-lab/mirdeep2/releases for new releases.

**Comment by mschilli87** [comment]
@sztankatt: ping

**Comment by mschilli87** [comment]
@sztankatt: There is yet another new version. We should really make sure to point people to github to avoid bug reports for long fixed bugs.

**Comment by Drmirdeep** [comment]
The Rajewsky lab webpage is unrelated to function of the miRDeep2 software package. Please use a different communication channel for keeping the outdated Rajewsky webpage up to date. This here refers to the miRDeep2 software only. Thanks.

**Comment by sztankatt** [comment]
@mschilli87 sorry, i dont really follow github, just seen this now. I wrote you an email
