### ISSUE TITLE
Allowed species 

### ISSUE THREAD

**Issue by kisun** [rajewsky-lab/mirdeep2#24]
Hi,

> The species Sheep you specified is not available
> allowed species are
> .....
> 

Is there alternative way to include Sheep? Earlier, I had no issue in analyzing sheep miRNA data.

Thanks,
Kisun

**Comment by mschilli87** [comment]
@kisun: Yet again, there is absolutely no way for us to reproduce your problem.
As you pointed out, miRDeep lists all the allowed species. But for some reason, you decided not to share that part with us. Again, there is no way of knowing which version you use, which system you are on, how you installed miRDeep2, how you called miRDeep2 (*full* command line *plus* example data).
And what does 'earlier' mean? This morning? Yesterday afternoon? Five years ago with an older version of miRDeep2 and different input files?

We are happy top help but we are not paid to guess what you are trying to achieve and write the code for you. Personally, I'm going to ignore any feature issue from you starting with this one that does not convince me that you have at least tried to solve the problem yourself and made an effort to make it easy for me to reproduce your exact error so I can help.

**Comment by mschilli87** [comment]
For anyone else running into this issue: I *suspect* everything is fine and the secret part of @kisun's error message actually contains *Ovis Aries*. So probaly specifying that or `oar` (which is the prefix all sheep miRNAs start with) is the solution to the problem. But *maybe* @kisun has done everything correctly and there is a bug in miRDeep2. Without more information there is no way to tell.

**Comment by Drmirdeep** [comment]
You can also just omit the species specification. However, ucsc links and mirbase links may not be created.
