### ISSUE TITLE
mapper.pl 

### ISSUE THREAD

**Issue by LliliansCalvo** [rajewsky-lab/mirdeep2#25]
Hi, 

I am using mapper.pl to map reads (fast) to a genome index generated with bowtie. The command looks like: 
mapper.pl file.fastq -e -h -m -p INDEX -s collapsed_reads.fa -t reads_collapsed_vs_genome.arf

The problems arises because I am not getting 100% of the reads mapped, however, the initial input file (file.fastq) is made of reads I have previously mapped to the genome using bowtie and extracted the ones that mapped. 

bowtie command: bowtie  -v 1 -S -m 5 --best --strata -a INDEX raw_reads.fastq mapped.sam

I wonder how can I solve this and make mapper.pl mapped 100% of the reads since the only reason I am using mapper is to get a *.arf file so I can use mirdeep2.pl later on. 

Thanks for the help,
G

**Comment by mschilli87** [comment]
@LliliansCalvo: `grep bowtie $(which mapper.pl)` quickly reveals the following line:
https://github.com/rajewsky-lab/mirdeep2/blob/ee3417c8827000fb14132dae51fb7cec3ac84666/src/mapper.pl#L410

As you can see, miRDeep2 calls bowtie with different parameters than you did.
So I find it not surprising that you get different results from the two bowtie runs.

Even if you did use the same parameters, I'm not sure you can assume 100% reproducibility between bowtie runs as read mapping is a complex problem and bowtie might use some heuristics to speed up the mapping process.

Either way, this appears entirely unrelated to miRDeep2 but rather a question for the bowtie developers.

**Comment by Drmirdeep** [comment]
If your mapping file is in bowtie (version 1 own proprietary format) (not sam) you could in principle just run the convert_bowtie_output.pl on your mapping files. 
However, the mapper.pl also does some quality checking on the input sequences and filters them out. 
Further, a collapsed read file is produced which is absolutely essential for running the miRDeep2.pl so I cannot recommend the way you described it at all. You will then likely run into other issues when using the package.
