### ISSUE TITLE
Uninformative error for zero-mappings.

### ISSUE THREAD

**Issue by mschilli87** [rajewsky-lab/mirdeep2#27]
I actually hit the error I traced down in https://github.com/rajewsky-lab/mirdeep2/issues/9#issuecomment-398363550.
In the case of https://github.com/rajewsky-lab/mirdeep2/issues/9 it turned out an invalid index was used.
In my case however, I simply have an extraordinarily bad sRNA-seq run that actually doesn't seem to contain any miRNA reads.
While it is nice to see that miRDeep2 is specific enough to not report random miRNAs in this case, reporting '0 mapped' reads would clearly be better than failing with an error.

I know that running miRDeep2 on an input file without valid miRNA reads is pointless but this is one sample out of a big batch that I run through a standardized Snakemake workflow. Having to trace back that error and manually remove the sample to avoid errors seems pointless given the (supposedly) easy fix.

**Comment by Drmirdeep** [comment]
error reproduced and fixed

**Comment by mschilli87** [comment]
I still get

```
Use of uninitialized value $count2 in subtraction (-) at <path-to-quantifier.pl> line 459.
```

,

```
Use of uninitialized value $count2 in print at <path-to-quantifier.pl> line 459.
```

, and

```
Use of uninitialized value $count2 in multiplication (*) at <path-to-quantifier.pl> line 460.
```

with the [latest master](https://github.com/rajewsky-lab/mirdeep2/commit/15debf4e1b597276c2c6363d805aa3a7e64d5dfc).

Here are the offending lines: https://github.com/rajewsky-lab/mirdeep2/blob/15debf4e1b597276c2c6363d805aa3a7e64d5dfc/src/quantifier.pl#L459-L460

The patch I submitted as https://github.com/rajewsky-lab/mirdeep2/pull/28 took care of this.

**Comment by mschilli87** [comment]
I updated https://github.com/rajewsky-lab/mirdeep2/pull/28 to only fix the remaining issue (giving the copyright to @Drmirdeep).

**Comment by Drmirdeep** [comment]
Remove warning message about uninitialized value for count2 variable.
