### ISSUE TITLE
species not at UCSC

### ISSUE THREAD

**Issue by biopig** [rajewsky-lab/mirdeep2#30]
i want to analysis the mirna-seq of rice, but when i use quantifier.pl, i found that rice didn't at UCSC, so is there any solutions to use quantifier.pl.

**Comment by mschilli87** [comment]
@biopig: Have you tried not specifying the species? Obviously you can't get (working) UCSC links in the HTML output, but as long as you specify the rice miRNAs, quantification should be possible.
If you don't get it to work, please provide a small reproducible example (incl. all required input data and the exact command(s) you tried). Also, don't forget to share which version of miRDeep2 you are using and how you installed it if you come back for further advice.

**Comment by biopig** [comment]
Can you give me you email?

**Comment by mschilli87** [comment]
Please provide a script here instead that downloads all data from public sources.
If you can not reproduce this with any publicly available rice dataset and your dataset is private, you can upload a handful of reads (obfuscated any way you like).

This way, you don't rely on me solving this as others (like @drmirdeep) can give it a shot, too.

Also, if someone later comes across a situation like this, they can use your example to verify they get the same results so any solution to your problem is likely a solution to theirs.

**Comment by biopig** [comment]
it's same that my problem seem to [#26](https://github.com/rajewsky-lab/mirdeep2/issues/26), but my error is
`quantifier.pl -p ../reference/osa_hairpin.fa -m ../reference/mature_osa.fa  -r COI_1_collapse.fa   -y 04_03_2019_t_20_01_10 -k
#Quantitation of known miRNAs in data
getting samples and corresponding read numbers

Converting input files
building bowtie index
mapping mature sequences against index
mapping read sequences against index
Mapping statistics

#desc   total   mapped  unmapped        %mapped %unmapped
total: 17979820 78223   17901597        0.435   99.565
seq: 17979820   78223   17901597        0.435   99.565
analyzing data
Expressed miRNAs are written to expression_analyses/expression_analyses_04_03_2019_t_20_01_10/miRNA_expressed.csv
not expressed miRNAs are written to expression_analyses/expression_analyses_04_03_2019_t_20_01_10/miRNA_not_expressed.csv

Creating miRBase.mrd file

Use of uninitialized value in print at /disks/workin/zwm/biosoft/mirdeep2-master/src/quantifier.pl line 1285, <IN> line 9157.
Use of uninitialized value $skeys[0] in hash element at /disks/workin/zwm/biosoft/mirdeep2-master/src/quantifier.pl line 1359, <IN> line 9157.
Use of uninitialized value in print at /disks/workin/zwm/biosoft/mirdeep2-master/src/quantifier.pl line 1285, <IN> line 9157.
Use of uninitialized value $skeys[0] in hash element at /disks/workin/zwm/biosoft/mirdeep2-master/src/quantifier.pl line 1359, <IN> line 9157.
`
my command is 
- miRDeep2.pl COI_1_collapse.fa ../reference/Oryza_sativa.fa COI_1.arf ../reference/mature_osa.fa ../reference/mature_all.fa ../reference/osa_hairpin.fa
my mirdeep2 is the latest release version of 2.0.1.2


-

**Comment by mschilli87** [comment]
@Drmirdeep:

Looks like those are `hash` and `skeys[0]`:
https://github.com/rajewsky-lab/mirdeep2/blob/dc71ea882ef1e92aaf2cd8baf47361c1b8c3b7ee/src/quantifier.pl#L1285
https://github.com/rajewsky-lab/mirdeep2/blob/dc71ea882ef1e92aaf2cd8baf47361c1b8c3b7ee/src/quantifier.pl#L1359

Do you want me to give it a shot or do you want to fix those?

---
@biopig: Can you provide links to `../reference/osa_hairpin.fa`, `../reference/mature_osa.fa`, and (some line of) `COI_1_collapse.fa`?
This would enable us to reproduce your issue locally and verify our fix works without haveing to go back and forth with you for every attempt.

**Comment by biopig** [comment]
I want to know if this question affects the final result.
This example is some line of my file.
Thank you.
[example.zip](https://github.com/rajewsky-lab/mirdeep2/files/2929023/example.zip)

**Comment by mschilli87** [comment]
@biopig:
Thx for getting back.

However, we could spend more time actually investigating your problem if you could help us even more to spend less time reproducing it.
Ideally, you'd provide a little bash script (in verbatim) that we can copy/paste to a (GNU/Linux) terminal and get your error.

That script should start by downloading your miRNA reference and read FASTAs and the run the quantifier module as you described above.

If you can't help us any further, we likely have everything to get there eventually, but it will take longer until we get there (and from there to a solutio for you). :wink:

**Comment by Nourolah** [comment]
I am using the older version (2.0.0.8), and I received the same error before PDF generation. But, you are right; the `csv` file is created and all the miRNA quantification is processed.

**Comment by Drmirdeep** [comment]
Your hairpin_osa.fa has linebreaks from windows or macos in it which are not properly converted by the script.

First of all, we need to use proper input files (good practice) 
extract_miRNAs.pl mature.fa osa > mature_osa.fa 
extract_miRNAs.pl hairpin.fa osa > hairpin_osa.fa 

To check if files are then valid to use please run
sanity_check_mature_ref.pl hairpin_osa.fa 
sanity_check_mature_ref.pl mature_osa.fa

if all is fine with the files you can rerun the quantifier.pl  

Apart from that, no read in your example file maps to any precursor thus you have 0 mappings and thus there are warning messages showing up all regarded to this. I updated the quantifier.pl to take care of precursors with 0 reads mapped to it.
