### ISSUE TITLE
Unique novel miRNA identifier

### ISSUE THREAD

**Issue by Nourolah** [rajewsky-lab/mirdeep2#31]
Hi,

I am using miRDeep2 version 2.0.08, and all the generated output are fine and I have all the known and novel miRNAs. The question I have here is that, when I want to use novel miRNAs total counts to analyze their expression pattern (control samples vs treated samples), each novel miRNA id has a unique identifier. The major issue is that when I am importing the data into a software like DESeq2 to identify differential expressed miRNA, because all the identifiers among the samples (controls and treatments) are unique, software is not able to perform normalization and other downstream analysis and the reason is due to difference in `factor levels`

I am not sure there is a way to generate output in miRDeep2 as HTSeq does (one column gene id, second column read counts) among all the samples. miRDeep2 maps the reads against the reference genome, but for each sample generate a unique identifier like `NW_018742577.1_6527`, which makes the downstream analysis nearly impossible. The numbers after `_` are unique in all the samples, so that's the reason all the samples have different factor levels.

I also checked the `.bed` files of the samples, they have the scaffold ID like `NW_018742577.1`, but then I have to look for thousands of gene coordination to see the similarity of the predicted novel miRNA. Which is sort of life-long work!

Any help or suggestion to fix the output identifier is appreciated.

**Comment by mschilli87** [comment]
I don't really see this as an issue with miRDeep2 but rather with the downstream analysis:
Each miRDeep2 run gives you a list of potential novel miRNAs. I'd consider them candidates and not 'the truth'. I also don't see the point in running the novel prediction per sample/condition (Other than adding samples at a later stage without re-running the whole analysis). Also, I think it doesn't make sense to treat 'novel' miRNAs any different from 'known' ones with respect to differential expression analyses.

What I would propose as workflow is the following:

1. Predict novel miRNA candidates using miRDeep2.
2. Filter down the list (by your own means; could involve validation experiments, random reads as negative controls, ...) to a set your believe are real (and relevant to your biological question).
3. Add those novel miRNAs to the known ones (typically obtained from miRbase).
4. Quantify all miRNAs using miRDeep2 (treating them equal).
5. Perform downstream analyes (DE etc.).

While one *could* run the first step per sample and merge predictions in the second one (merging by coordinates, not ID), I'd merge all samples for the novel prediction (combining all data available to maximize power) but keep them separate for the quantification (to get per-sample/condition abundance estimates).

I hope this answers your question so I'm closing this issue. You can still reply/re-open the issue if you disagree.

**Comment by Nourolah** [comment]
Thanks for your comments.

Actually, I have already quantified miRNA from individual samples using miRDeep2 and have the number of read counts per each novel and known miRNA separately. I have also merged all the novel miRNAs by 'bedtools', which shows which novel miRNA belong to which coordinate of the genome. 

Now, assuming that I am considering all the novel miRNAs detected as **true**, how I could add novel miRNA counts to the table of known miRNA while the novel ones have different identifier per sample? Like the column 4 of example below.

```
NW_018742205.1	4848180	4848254	"novel:NW_018742205.1_1191,novel:NW_018742205.1_1223,novel:NW_018742205.1_1266,novel:NW_018742205.1_1283,novel:NW_018742205.1_1290,novel:NW_018742205.1_1294,novel:NW_018742205.1_1301,novel:NW_018742205.1_1309,novel:NW_018742205.1_1326"
NW_018742205.1	7335922	7335986	"novel:NW_018742205.1_1209,novel:NW_018742205.1_1259,novel:NW_018742205.1_1271,novel:NW_018742205.1_1279,novel:NW_018742205.1_1289,novel:NW_018742205.1_1291,novel:NW_018742205.1_1293,novel:NW_018742205.1_1311,novel:NW_018742205.1_1315,novel:NW_018742205.1_1321,novel:NW_018742205.1_1325,novel:NW_018742205.1_1337,novel:NW_018742205.1_1339,novel:NW_018742205.1_1341,novel:NW_018742205.1_1343,novel:NW_018742205.1_1357,novel:NW_018742205.1_1361,novel:NW_018742205.1_1367,novel:NW_018742205.1_1369,novel:NW_018742205.1_1371,novel:NW_018742205.1_1375,novel:NW_018742205.1_1383,novel:NW_018742205.1_1387,novel:NW_018742205.1_1393,novel:NW_018742205.1_1405,novel:NW_018742205.1_1411,novel:NW_018742205.1_1419,novel:NW_018742205.1_1429"
NW_018742205.1	7804495	7804585	"novel:NW_018742205.1_1228,novel:NW_018742205.1_1280,novel:NW_018742205.1_1306,novel:NW_018742205.1_1308,novel:NW_018742205.1_1320,novel:NW_018742205.1_1334,novel:NW_018742205.1_1346,novel:NW_018742205.1_1376,novel:NW_018742205.1_1386,novel:NW_018742205.1_1392,novel:NW_018742205.1_1404,novel:NW_018742205.1_1424,novel:NW_018742205.1_1426,novel:NW_018742205.1_1438,novel:NW_018742205.1_1448,novel:NW_018742205.1_1536,novel:NW_018742205.1_1626,novel:NW_018742205.1_1658,novel:NW_018742205.1_1684,novel:NW_018742205.1_1738,novel:NW_018742205.1_1740,novel:NW_018742205.1_1764,novel:NW_018742205.1_1784,novel:NW_018742205.1_1786,novel:NW_018742205.1_1820"
NW_018742205.1	2730116	2730171	novel:NW_018742205.1_1238
NW_018742205.1	4840115	4840204	novel:NW_018742205.1_1572
NW_018742205.1	4110643	4110718	"novel:NW_018742205.1_1603,novel:NW_018742205.1_1629"
NW_018742205.1	4548487	4548540	novel:NW_018742205.1_1655
NW_018742205.1	8109058	8109112	novel:NW_018742205.1_1693
NW_018742205.1	6805156	6805222	novel:NW_018742205.1_1707
NW_018742238.1	471179	471261	novel:NW_018742238.1_1751
NW_018742238.1	909899	909980	novel:NW_018742238.1_1792
NW_018742238.1	722527	722612	novel:NW_018742238.1_1856
NW_018742238.1	2026211	2026265	"novel:NW_018742238.1_1892,novel:NW_018742238.1_1954"
NW_018742241.1	725783	725907	"novel:NW_018742241.1_1792,novel:NW_018742241.1_1907"
NW_018742241.1	787053	787105	"novel:NW_018742241.1_1918,novel:NW_018742241.1_1990,novel:NW_018742241.1_1998"
```

I am asking this because I am going to prepare a datamatrix containing novel and known miRNA as an input for DE analysis. Do you think should I just use the first novel miRNA id in the column 4 and rename the rest in that row to first one's name? Or is there any simpler way to do this?

I really appreciate your time and helps!

**Comment by mschilli87** [comment]
@Nourolah:
> Do you think should I just use the first novel miRNA id in the column 4 and rename the rest in that row to first one's name? Or is there any simpler way to do this?

I usually just assign my own IDs (nov-1, nov-2, etc.).
The only 'easier' way I can come up with would be to to predict novel miRNAs on merged data so each candidate is detected only once and therefore gets only one ID to begin with.
As long as you run miRDeep2 several times (*i.e.* per sample) there is no way for one instance to know if a novel miRNA will be found by another instance and which ID will be assigned.

So if you look for an easy way out from what you have, merging and assigning your own IDs would be fine. In general (for others finding this issue or your next run) I'd recommend the workflow I outlined above for the aforementioned reasons.

**Comment by Nourolah** [comment]
Thanks for your feedback.
