### ISSUE TITLE
quantifier.pl -w error: "Mature mapping file hairpin_sfr.fa.dummy_mapped.bwt not found"

### ISSUE THREAD

**Issue by hmontenegro** [rajewsky-lab/mirdeep2#34]
I am using miRDeep2-0.1.2. When running `quantifier.pl -w`:

```
quantifier.pl -k -w -p ../index/hairpin_sfr.fa \
    -m ../index/mature_sfr.fa \
    -r reads_collapsed.fa &>quantifier_run1.log
```

I get the following error, and no quantification is performed:

> Mature mapping file hairpin_sfr.fa.dummy_mapped.bwt not found 

However, without `-w`, `quantifier.pl` runs without errors and generates all expected files:

```
quantifier.pl -k -p ../index/hairpin_sfr.fa \
    -m ../index/mature_sfr.fa \
    -r reads_collapsed.fa &>quantifier_run2.log
```

**edit:** if needed, I can work out a script to reproduce the issue.

**Comment by mschilli87** [comment]
@hmontenegro:
>  if needed, I can work out a script to reproduce the issue.

That would be great. :heart:

**Comment by hmontenegro** [comment]
:lau

> @hmontenegro:
> 
> > if needed, I can work out a script to reproduce the issue.
> 
> That would be great. heart

Ok, I'll work out a reproducible example later today or tomorrow (or longer, due to holiday). I hope I can reproduce the issue with publicly available data :rofl:

**Comment by Drmirdeep** [comment]
for what purpose did you use option w? Apart from that it does not make sense to use option w together with option m. Anyhow, the option w is deprecated and will be removed.

**Comment by Drmirdeep** [comment]
Likely

**Comment by mschilli87** [comment]
@Drmirdeep 
> Apart from that it does not make sense to use option w together with option m.

Maybe a more informative error message would resolve this then?

**Comment by hmontenegro** [comment]
It is with great shame I must announce this was (at least partially) a great PEBCAK issue. I intended to use `-W`, however, sadly I used `-w`. All is well now that I used the correct argument.

On the other hand, `-w` seems to fail no matter how I try it, always with "Mature mapping file hairpin_sfr.fa.dummy_mapped.bwt not found". How `-w` should be used? Bellow are the commands to replicate the issue:

```
##### Install miRDeep2 0.1.2 #####

mkdir -p ~/bin/miRDeep2
cd ~/bin/miRDeep2/
curl -L https://github.com/rajewsky-lab/mirdeep2/archive/v0.1.2.tar.gz -o mirdeep2-0.1.2.tar.gz
tar -x -z -f mirdeep2-0.1.2.tar.gz
cd mirdeep2-0.1.2/
perl install.pl
source ~/.bashrc
perl install.pl
cd ~

##### Create analysis directory tree #####

mkdir -p ~/mirdeep2_issue34/{index,fastq,analysis}
mkdir ~/mirdeep2_issue34/index/{genome,mirbase}

##### Prepare references #####

cd ~/mirdeep2_issue34/index/genome/
wget http://bipaa.genouest.org/data/public/sfrudb/corn_assembly_v3.1_20141112/sfru.mais.corrected.3.1.fa
bowtie-build sfru.mais.corrected.3.1.fa sfru_corn-3.1

cd ~/mirdeep2_issue34/index/mirbase/
wget ftp://mirbase.org/pub/mirbase/22.1/hairpin.fa.gz
wget ftp://mirbase.org/pub/mirbase/22.1/mature.fa.gz
gunzip *gz

extract_miRNAs.pl mature.fa sfr mature > mature_sfr.fa
extract_miRNAs.pl mature.fa bmo,bte,hme,pxy,mse mature > mature_lepi.fa
extract_miRNAs.pl mature.fa sfr star > star_sfr.fa
extract_miRNAs.pl hairpin.fa sfr > hairpin_sfr.fa

##### Get some miRNA sequencing data #####

cd ~/mirdeep2_issue34/fastq/
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR153/008/SRR1536058/SRR1536058.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR153/009/SRR1536059/SRR1536059.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR153/000/SRR1536060/SRR1536060.fastq.gz
gunzip *.gz

##### Create config file #####

cd ~/mirdeep2_issue34/analysis/
cat > config.txt << EOF
../fastq/SRR1536058.fastq CT1
../fastq/SRR1536059.fastq CT2
../fastq/SRR1536060.fastq CT3
EOF

##### Run miRDeep2 #####

mapper.pl config.txt -e -d -h -j -l 18 -m -o 1 \
    -s collapsed.fa -t mirna_sfr.arf -u -v \
    -p ../index/genome/sfru_corn-3.1

quantifier.pl -w -k -p ../index/mirbase/hairpin_sfr.fa \
    -m ../index/mirbase/mature_sfr.fa \
    -r collapsed.fa

quantifier.pl -w -k -p ../index/mirbase/hairpin_sfr.fa \
     -r collapsed.fa

quantifier.pl -w -p ../index/mirbase/hairpin_sfr.fa \
     -r collapsed.fa

quantifier.pl -P -w -p ../index/mirbase/hairpin_sfr.fa \
     -r collapsed.fa
```

**Comment by Drmirdeep** [comment]
Yes, it fails always because it is only half implemented and was not meant for public usage yet. It was a short cut for not needing to run a different mapping tool alone on the precursors only. Anyhow,
issue is resolved. Have a nice Easter!
