### ISSUE TITLE
All candidates discarted "because the structure is inconsistent with Dicer processing"

### ISSUE THREAD

**Issue by OnlyHigh** [rajewsky-lab/mirdeep2#37]
Hi, apparently one of the issues of #36 was because my output files were empty,
When I checked the ```error.output.mrd``` file, 
All my candidate miRNA were discarded "because the structure is inconsistent with Dicer processing", find the file attached, 
[error.output.mrd_31_05_2019_t_15_41_43.txt](https://github.com/rajewsky-lab/mirdeep2/files/3242841/error.output.mrd_31_05_2019_t_15_41_43.txt)

Is this normal? which is the choosing criterion? 
Cheers, 
Luis Alfonso.

**Comment by Drmirdeep** [comment]
Hi Luis, 

this usually appears if the reads you are using do not correspond to putatively valid mature miRNA sequences or if your precursors are simply not fulfilling the criteria for miRNA precursors which also traces back to the reads you are initially using...  Have a look at the tutorial files and the pdfs and see how the reads there align to the predicted hairpin structures...

Cheers,
Sebastian
