### ISSUE TITLE
miRDeep2 does not generate result.html 

### ISSUE THREAD

**Issue by sridewi1** [rajewsky-lab/mirdeep2#38]
Hi, 

unfortunately I could not find `result.html`  or `result.csv` in the result directory  after miRDeep2.pl command. Strangely I did not get any errors but this result is missing.

here are the generated files I got
![grafik](https://user-images.githubusercontent.com/24940249/61466456-39108900-a97a-11e9-9b6c-ff4a157088b5.png)

and here is command line screenshot, which looks just fine without any errors
![grafik](https://user-images.githubusercontent.com/24940249/61466840-e5eb0600-a97a-11e9-841c-61843735b987.png)

I deeply appreciate any kind of help. 
Dewi

**Comment by mschilli87** [comment]
Dear Dewi,

We won't be able to help without being able to reproduce your error.

* Which operating system are you on?
* How did you install miRDeep2?
* Does it work with the test data provided alongside miRDeep2?
* What is the command you are running?
* Can you reproduce the error using just a small fraction of your input data?
* Can you share that fraction of you input data with us so we can debug?

When you post commands, please make sure to provide them as text that we can copy/paste to try ourselves, not as screenshots from terminals that require us to re-type everything. :wink:

Best,
Marcel

**Comment by mschilli87** [comment]
PS: Also, could you share please share the content of `error_[...].log` (can't copy from your screenshot, won't scroll up and down to actually type it out) with us? :wink:

**Comment by sridewi1** [comment]
Dear Marcel,

thanks for the prompt answer. 

   

>  Which operating system are you on?

I am using Ubuntu 18.04.2 LTS
 

>    How did you install miRDeep2?

I installed miRDeep2 by downloading the github repository and excecuted the `perl install.pl` 


>   Does it work with the test data provided alongside miRDeep2?

It did work but also I coudn't not find `result.html` and `result.csv` using the provided test data


>     What is the command you are running?

firstly I mapped the data using mapper.pl with followings parameters

`mapper.pl  unmapped.fastq -e -h -m -p bowtie_index -s mapped.collapsed.fa -t mapped.collapsed.arf -v -o 10 1>&2 mapped.mapper.log` 

and proceeded further with miRDeep2.pl 

`miRDeep2.pl mapped.collapsed.fa Mus_musculus.GRCm38.94.fa mapped.collapsed.arf mature_mmu_ref.fa mature_hsa_rno_ref.fa hairpin_mmu_ref.fa -t Mouse 2> mapped.report.log`


> Can you share that fraction of you input data with us so we can debug?

Sure, I attached the first 100 reads and the corresponding arf data for one sample. 
[E14F1_collapsed_100.zip](https://github.com/rajewsky-lab/mirdeep2/files/3410428/E14F1_collapsed_100.zip)

> When you post commands, please make sure to provide them as text that we can copy/paste to try ourselves, not as screenshots from terminals that require us to re-type everything

I am sorry it doesn't came in to my mind. I will try to always provide them as text :) 
Thanks a lot for your help!

Dewi

**Comment by sridewi1** [comment]
> PS: Also, could you share please share the content of `error_[...].log` (can't copy from your screenshot, won't scroll up and down to actually type it out) with us? 

Sure, I also attached the error.log file 
[error_18_07_2019_t_13_39_59.log](https://github.com/rajewsky-lab/mirdeep2/files/3410783/error_18_07_2019_t_13_39_59.log)

**Comment by Drmirdeep** [comment]
If the tutorial data doesn't even work then something is definitely wrong

Please go in the tutorial directory and run 
'bash run_tut.sh &> tutorial.log'
and upload the file here.

Best,
Sebastian

**Comment by sridewi1** [comment]
Dear Sebastian,

Sorry for the late reply, I was on holiday last week. I attached the log file. 
[tutorial.log](https://github.com/rajewsky-lab/mirdeep2/files/3451728/tutorial.log)

thanks a lot for your help!

cheers,
Dewi

**Comment by Drmirdeep** [comment]
Hi, 
I cannot see any issues. I noticed that you have the mirdeep2_patch in your path which uses an outdated make_html.pl by now. I would propose to do a clean install by running
git clone https://github.com/rajewsky-lab/mirdeep2.git

and in the new mirdeep2 directory running

perl install.pl 

You can run this as a local user . 
Let us know if this helps.

Cheers,
Sebastian

**Comment by sridewi1** [comment]
Dear Sebastian,

I re-installed the new mirdeep2 as you suggested and It's finally working now.  

Thank you so much for your help!

Best,
Dewi
