### ISSUE TITLE
how to da data processing

### ISSUE THREAD

**Issue by leiwaaping** [rajewsky-lab/mirdeep2#39]
seeming that mapper.pl will do data process automatically， including a specific adaptor sequence. we input a SE50 fasta file(it did QC advanced and seems no adaptor already),and still gain a result fasta file with 50bp sequence. 
raw data:
![image](https://user-images.githubusercontent.com/47714000/62260123-7af20280-b443-11e9-84b7-84bd9e9cc99a.png)
after mapper.pl:
![image](https://user-images.githubusercontent.com/47714000/62260024-159e1180-b443-11e9-81d1-0fe66709dbea.png)
some questions:
1)is it normal to have a 50bp sequence as input for the quantification module and the mirdeep2 module? will it be too long?
2)should I change U to T advanced? to convert RNA to DNA?
3)as for the output result, how to define a true mature miRNA, with a mirDeep2 score >0?
![image](https://user-images.githubusercontent.com/47714000/62261199-133db680-b447-11e9-9088-df92f2db55f2.png)

thanks

**Comment by Drmirdeep** [comment]
I am sorry but I this is unrelated to the miRDeep2 software. Please have a look at the papers describing what miRDeep2 does in particular. In general it identifies and uses reads from  the canonical miRNA biogenesis pathway and thus your finally processed reads need to have the same size as a typical mature miRNA sequence which is around 22nt in animals.

**Comment by leiwaaping** [comment]
thanks for your reply.
so what about the score? should I still keep the negative score miRNA?
best,Becca
    On Tuesday, August 6, 2019, 08:45:35 PM GMT+8, Sebastian Mackowiak <notifications@github.com> wrote:  
 
 
I am sorry but I this is unrelated to the miRDeep2 software. Please have a look at the papers describing what miRDeep2 does in particular. In general it identifies and uses reads from the canonical miRNA biogenesis pathway and thus your finally processed reads need to have the same size as a typical mature miRNA sequence which is around 22nt in animals.
