### ISSUE TITLE
Empty mapped ARF file

### ISSUE THREAD

**Issue by slzarate** [rajewsky-lab/mirdeep2#4]
I am using the example data and no files are empty. 

This is the call I'm using: `perl /opt/mirdeep2/src/mapper.pl reads.fa -c -k TCGTATGCCGTCTTCTGCTTGT -m -p cel_cluster -s reads_processed.fq -t reads_mapped.arf -v -n`

Here is the log:

```
clipping 3' adapters
discarding short reads
collapsing reads
mapping reads to genome index
trimming unmapped nts in the 3' ends
Log file for this run is in mapper_logs and called mapper.log_319
Mapping statistics
#desc	total	mapped	unmapped	%mapped	%unmapped
Use of uninitialized value $count2 in subtraction (-) at /opt/mirdeep2/src/mapper.pl line 709.
total: 378333	Use of uninitialized value $count2 in print at /opt/mirdeep2/src/mapper.pl line 709.
	378333	Use of uninitialized value $count2 in division (/) at /opt/mirdeep2/src/mapper.pl line 710.
Use of uninitialized value $count2 in division (/) at /opt/mirdeep2/src/mapper.pl line 710.
0.000	1.000
Use of uninitialized value in subtraction (-) at /opt/mirdeep2/src/mapper.pl line 712.
seq: 378333	Use of uninitialized value in print at /opt/mirdeep2/src/mapper.pl line 712.
	378333	Use of uninitialized value in division (/) at /opt/mirdeep2/src/mapper.pl line 713.
Use of uninitialized value in division (/) at /opt/mirdeep2/src/mapper.pl line 713.
```

**Comment by Drmirdeep** [comment]
Hi Samantha,

what is the output of running the install.pl script from the miRDeep2
package? Is everything installed properly? What is your mirdeep2 version
you are using?

Cheers,
Sebastian


--
Sebastian Mackowiak, Ph.D.
Friedländer Lab, Computational RNA Biology
The Wenner-Gren Institute, MBW

Science for Life Laboratory
Karolinska Institutet Science Park
Tomtebodavägen 23A
171 65 Solna
Sweden

**Comment by slzarate** [comment]
I thought it was successfully installed, but it is now giving me the message
`Use of uninitialized value $shell in pattern match (m//) at /opt/mirdeep2/install.pl line 31.` It was last updated December 3, 2017.

**Comment by Drmirdeep** [comment]
Please post the full output here of running the install.pl command and the content of 
./mapper_logs/mapper.log_319
