### ISSUE TITLE
miRDeep2.0.1.2 seem not to be working with Fastq

### ISSUE THREAD

**Issue by evnovaes** [rajewsky-lab/mirdeep2#44]
Hi, I have tested miRDeep2.0.1.2 and it seem not to be working with FastQ anymore.
I tried the following command:

_mapper.pl config.txt -d -e -o 15 -r 30 -n -h -j -q -l 17 -m -p bowtie_index/genome -s All_collapsed.fa -t Collapsed_vs_genome.arf -v_

It is returning with the following ERROR messages:
**Use of uninitialized value $query in pattern match (m//) at /usr/local/mirdeep2-master/bin/collapse_reads_md.pl line 129.
Use of uninitialized value $seq in transliteration (tr///) at /usr/local/mirdeep2-master/bin/collapse_reads_md.pl line 96.
Use of uninitialized value $seq in hash element at /usr/local/mirdeep2-master/bin/collapse_reads_md.pl line 97.**

 However, when I convert the fastq files to fasta, mapper.pl work just fine.

Thanks a lot,

**Comment by Drmirdeep** [comment]
looks like something is wrong in one of your sequences. however, without knowing what the problematic sequence is or what is in you input files it is hard to diagnose anything

you could run the same command with option -u and then check the tmp directory or just run the command on each single file separately and see where the problem occurs

**Comment by evnovaes** [comment]
I believe this is not the case, as the problem happens with all the input files. Just to test further I selected the first 10 fastq sequences of all my libraries/samples. The problem persists with all the sequences and libraries. Here is one of these first 10 sequences that I used as input:

**@HWI-D00447:183:CCU0EANXX:4:1101:1473:1959 1:N:0:TCCGTCTA
NTTAGTTGAACGTGGGCACT
+
#==ABGGGGGGGFGGFFDGG
@HWI-D00447:183:CCU0EANXX:4:1101:1422:1984 1:N:0:TCCGTCTA
NGCTCAATCTTTGGAAATCTC
+
#<<<:?F@F@BFGEGFF=FGF
@HWI-D00447:183:CCU0EANXX:4:1101:1742:1937 1:N:0:TCCGTCTA
NATGTCACCACGCGCGGGGATAGATCCTCT
+
#=AABFEGGGGGGGGGGGGGGGGGGGGGGG
@HWI-D00447:183:CCU0EANXX:4:1101:1621:1976 1:N:0:TCCGTCTA
NTCTCTATCTATTTGGCTCTT
+
#=ABBFGGGGGGGGGGGGGGG
@HWI-D00447:183:CCU0EANXX:4:1101:1516:1992 1:N:0:TCCGTCTA
NAGGCTGAAACTTAAAGAAA
+
#=ABBGGGGGGGGGGGGGGG
@HWI-D00447:183:CCU0EANXX:4:1101:1863:1939 1:N:0:TCCGTCTA
NCATCATTGGTCTAGTGGTAGAATTCAT
+
#<<ABFGGGGGGGGGFGGGGGGGGGGGG
@HWI-D00447:183:CCU0EANXX:4:1101:1878:1976 1:N:0:TCCGTCTA
NCAGATCTTGGTGGTAGTAGCAAATACTC
+
#<=:BGGGGGGGGDGGCGGGGGGGGGGGG
@HWI-D00447:183:CCU0EANXX:4:1101:1936:1983 1:N:0:TCCGTCTA
NTCCACGGCAACGTAACTGAAC
+
#<=ABBBGGGGGGGGGGGGGGG
@HWI-D00447:183:CCU0EANXX:4:1101:2319:1945 1:N:0:TCCGTCTA
NGTGATCCCGGGTCGAACGGCCTC
+
#=ABBGGGGGGGGGGGGGGGGGBG
@HWI-D00447:183:CCU0EANXX:4:1101:2582:1963 1:N:0:TCCGTCTA
NTGGGAATTTTTGAACAATTTT
+
#<<ABFGGGGGGGGGGGGGGGG**

 These sequences were obtained from a HiSeq 2500 machine and I cleaned (removed adapters) with Trimmomatic.
 Here is again the command line I used with these 10 sequences:

_mapper.pl Zn_3_trim.fq -e -o 15 -r 30 -n -j -h -q -l 17 -m -p /bowtie_index/genome -s All_collapsed.fa -t Collapsed_vs_genome.arf -v_

**Comment by evnovaes** [comment]
I must add that the miRDeep2 is running fine after I converted the FastQ reads into FASTA format.

**Comment by Drmirdeep** [comment]
When I take the few lines you provided and run 
 mapper.pl test.fq -e -h -j -l 17 -s All_collapsed.fa  
everything is fine.

What genome do you map to? 

What is written in the mapper log? Any hints there?

**Comment by evnovaes** [comment]
Thanks for looking into this.
I am using the Paracoccidioides brasiliensis Pb18 genome indexed with bowtie. The genome can be downloaded here: https://mycocosm.jgi.doe.gov/Parbra1/Parbra1.home.html

 But if you want I can send you the genome. It was 30Mb uncompressed.

I looked at one of the mapper_logs but found nothing. Here is one log file:

**#############################################
mapper command:	/usr/local/mirdeep2-master/bin/mapper.pl Zn_3_trim.fq -e -o 15 -r 30 -n -j -h -q -l 17 -m -p /home/celia/genoma/bowtie_index/Pb_genome -s All_trimmomatic_collapsed.f
a -t All_collapsed_vs_genome.arf -v

timestamp:	04_09_2019_t_10_11_47

parsing fastq to fasta format
fastq2fasta.pl Zn_3_trim.fq > dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads.fa
discarding sequences with non-canonical letters
fastaparse.pl dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads.fa -b > dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_letters.fa 2>dir_mapper_s
eq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_discarded.fa
discarding short reads
fastaparse.pl dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_letters.fa -a 17 > dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_no_short.fa 2>
dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_too_short
collapsing reads
collapse_reads_md.pl dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_no_short.fa seq > dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_nr.fa
mapping reads to genome index
bowtie -p 15 -f -n 1 -e 80 -l 18 -a -m 30 --best --strata /home/celia/genoma/bowtie_index/Pb_genome  --al dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/Zn_3_trim.fq_m
apped --un dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/Zn_3_trim.fq_not_mapped  dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_nr.fa dir_mapper_
seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/mappings.bwt 2>bowtie.log

convert_bowtie_output.pl dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/mappings.bwt > dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/mappings.arf
trimming unmapped nts in the 3' ends
parse_mappings.pl dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/mappings.arf -j > dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/mappings_trim.arf

remove tmp dir
rmtree(dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47)

############################################################**

The bowtie log might say more as it found no read in the converted fasta file. See log below:

**############################################################
Warning: Could not find any reads in "dir_mapper_seq_Zn_3_trim.fq_5040693826_04_09_2019_t_10_11_47/reads_nr.fa"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)
No alignments
############################################################**

**Comment by Drmirdeep** [comment]
Apparently none of your reads maps to the genome. Could you verify that it is the correct one?
When I add a single read that matches then there is of course normal output.
I donwloaded the genome from ensembl
I just added this.
@HWI-D00447:183:CCU0EANXX:4:1101:1473:1959 1:N:0:TEST
AATTTATAAAGCTATATATATATTTAATG
+
GGGGGGGGGGGGGGGGGGGGGGGGGGGGG

You can also have a look at the tmp folder and see which files are not created. With your test reads the mapping file was empty since nothing mapped. 
For this you need to run it with option -u

**Comment by mschilli87** [comment]
@evnovaes: Any update on this?

**Comment by Drmirdeep** [comment]
The update is that likely all the reads contain at least a single mismatch and thus nothing is mapped with the current bowtie settings in the initial mapping. Remove all Ns in the beginning and end and then it should work.

**Comment by evnovaes** [comment]
I beg your pardon for not replying to the last messages. I have been busy and could not do any further testing lately. I am professor, in addition to bioinformatician apprentice. I will resume the analyses next week. You may close this problem, as you have not been able to replicate the reported problem.
