### ISSUE TITLE
I got two different result when running miRDeep2 core  algorithm twice

### ISSUE THREAD

**Issue by Peiyao-Nie** [rajewsky-lab/mirdeep2#45]
I ran miRDeep2 core algorithm twice using human data.I got a novel miRNA from the first result and some verification work had been done.However, I can not find this novel miRNA in second result.The criteria for identifying the same small RNA is they have same precursors that is from same genome loci, same mature sequence, same star sequence.I check the detailed information and find the novel miRNA has the different score, 2 in first and -1.7 in second. The score cut-off I set is 0. The miRNA  that score>0 predicted by miRDeep2 core algorithm is the final miRNA How can I explain it?

**Comment by mschilli87** [comment]
IIRC, the score is calculated on a random shuffling background model and this might change (slightly) from run to run. So I'm not sure that you can expect a miRNA to score exactly the same across runs.
If you have experimental evidence of the miRNA existing in your system of interest, why would you care whether or not it pops up in some prediction list at all? And if you don't have any supporting evidence, a candidate that is not reproducibly predicted is more likely to be a false-positive so I'd rather focus on those that can.

I'll leave this open in case @Drmirdeep has something more profound to contribute. :wink:

**Comment by Peiyao-Nie** [comment]
Thanks for your reply.
Another question is that I comapred all novel miRNAs between the two results and about 20% of all novel miRNA in first run can not be predicted(score > 0) while another new 20% novel miRNAs were predicted in second run.This results in the numer of total novel miRNAs is little different but the content not.The percent is too big for me.Some means can use to make the percent lower?
It should be noted that I make some little change based on the standard pipline.First,I use Quantifier module to quantify known mature miRNA using all reads in samples.Second,The sequencing reads that were not mapped to known miRNA precursor were used to predict novel miRNA.
Look forward to your reply.

**Comment by mschilli87** [comment]
@Peiyao-Nie: I think this goes beyond what we can offer as support for software published several years ago by our lab. Please read the corresponding paper and draw your own conclusions for your analyses. This is an issue tracker for problems with the software which yuou don't seem to encounter.

**Comment by Peiyao-Nie** [comment]
Ok.Thank you all the same.
