### ISSUE TITLE
Output bed files (press, mature and star) have the same coordinates 

### ISSUE THREAD

**Issue by LliliansCalvo** [rajewsky-lab/mirdeep2#46]
Hi, 
After running mirdeep2 and predicting microRNAs I've realised the 3 bed files have exactly the same positions:

examples:
 **mature bed file** 
LQNS02278089.1	**848170	848230**	LQNS02278089.1_34108	2249659.3	-	848170	848230	0,0,255
LQNS02278089.1	**847652	84771**1	LQNS02278089.1_34106	1566285.5	-	847652	847711	0,0,255

**precursor bed file**
LQNS02278089.1	**848170	848230**	LQNS02278089.1_34108	2249659.3	-	848170	848230	0,0,255
LQNS02278089.1	**847652	847711**	LQNS02278089.1_34106	1566285.5	-	847652	847711	0,0,255

Therefore I am blocked at this stage. 
How could I get a bed file containing the coordinates of the mature sequence, or the star sequences, not just the precursor sequences coordinates three times. 

Thanks for the help!

**Comment by Drmirdeep** [comment]
seems like this is not implemented yet. You can use bowtie or perl or python and get the position of the mature and star in the precursor.

**Comment by Drmirdeep** [comment]
Updated
