### ISSUE TITLE
Detect synthetic miRNA via miRDeep2

### ISSUE THREAD

**Issue by dinggens** [rajewsky-lab/mirdeep2#47]
Hello,

I have a question regarding the detection of synthetic miRNA.
So far I have been using _miRDeep2_ for biological data and it worked fine.
Now, synthetic miRNA are not detected/counted, although I adapted the input files accordingly by adding the synthetic miRNA to the reference files ($genome, $mature) for mapper.pl and quantifier.pl:

mapper.pl ${sampleid}.fq -e -h -m -l 18 -s ${sampleid}/collapsed.fa
mapper.pl ${sampleid}/collapsed.fa -c -p $genome -t $${sampleid}/mapped.arf 
quantifier.pl -p $hairpin -m $mature -r ${sampleid}/collapsed.fa -t $spshort

Is it possible that also the precursors ($hairpin) have to be adapted?

Many thanks in advance

**Comment by mschilli87** [comment]
@dinggens:
> Is it possible that also the precursors ($hairpin) have to be adapted?

Yes.

---
PS: This is an issue tracker for bugs with the software. For more general questions regarding how to perform specific analyses, please consider more general Q&A platforms like [Biostars](https://www.biostars.org/) or [Biology SE](https://biology.stackexchange.com/).
