### ISSUE TITLE
miRNA normalization based on total reads includes multiple mapped reads

### ISSUE THREAD

**Issue by andreasd** [rajewsky-lab/mirdeep2#49]
Hi!

I was just checking how exactly miRDeep2 calculates the normalized reads column (seq(norm)) and read in the FAQ that it is a simple RPM calculation where the lib size is the number of reads mapped against precursors.

This number of reads includes reads that map against multiple precursors and also counts those multiple times. If there are 10 reads that map against 2 precursors the library size is 20. 

This will lead to library size variations depending on the miRNA profile. If there are miRNAs overexpressed that have multiple precursors, the library size will be larger. 

I would thus suggest to take the sum of all unique mapped reads for the calculation of RPM, as the RPM normalization is aiming to normalize for sequencing library size and should not be dependent of the sequences found.

**Comment by mschilli87** [comment]
Hi @andreasd,

Your concerns are reasonable but as always, there is no 'best' way to handle things.
If we were to actively develop miRDeep2 this would be valuable input.
At this point however it would change the result of analyzing the same data
with the current versus the next release which would create in many new issues
for us to handle which we don't have time to.

For responsible scientist that understand the details and care (like you
do), miRDeep2 provides the raw counts that can be normalized anyway the
user wants downstream.

**Comment by andreasd** [comment]
Hi!

I totally agree with your arguments but then might suggest to add this to the documentation/faq. In the end it probably won't make a big difference (if any) on most experiments, but it would help if people care and wonder why their calculations are off.

thanks,
andreas

**Comment by mschilli87** [comment]
In this case they hopefully search closed github issues before opening a new one or simply read the code. :wink:
