### ISSUE TITLE
Issue changing Make_html.pl

### ISSUE THREAD

**Issue by Jammcgro123** [rajewsky-lab/mirdeep2#5]
Hi,
I am an admin on a current HPC cluster and one of our users is trying to use this software. I have created a job script but it fails when run. See following error : 

```
"mkdir: cannot create directory `/opt/apps/mirdeep2_0_0_8/src/indexes': Permission denied
Could not open index file for writing: "/opt/apps/mirdeep2_0_0_8/src/indexes/Rfam_index.3.ebwt"
Please make sure the directory exists and that permissions allow writing by
Bowtie.
Command: bowtie-build --wrapper basic-0 /opt/apps/mirdeep2_0_0_8/src//../Rfam_for_miRDeep.fa /opt/apps/mirdeep2_0_0_8/src/indexes/Rfam_index
Settings:
  Output files: "/opt/apps/mirdeep2_0_0_8/src/indexes/Rfam_index.*.ebwt"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 5 (one in 32)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  /opt/apps/mirdeep2_0_0_8/src//../Rfam_for_miRDeep.fa
Reading reference sizes
  Time reading reference sizes: 00:00:00
Total time for call to driver() for forward index: 00:00:00
 
Rfam index could not be created in /opt/apps/mirdeep2_0_0_8/src/indexes/
Please check if miRDeep2 is allowed to create the directory /opt/apps/mirdeep2_0_0_8/src/indexes/ and write to it
The Rfam analysis will be skipped as long as this is not possible"
``` 

---
I have tracked this down to that the user does not have permission to create and write "indexes" to "src" directory. Is there any way possible that we can change the path of where the indexes directory is created via command line or job script? i am using centos linux.

**Comment by Drmirdeep** [comment]
Hi,
the easiest solution would be to generate the index files bye you once in 
/opt/apps/mirdeep2_0_0_8/src/indexes/

## The command is already given
bowtie-build --wrapper basic-0 /opt/apps/mirdeep2_0_0_8/src//../Rfam_for_miRDeep.fa /opt/apps/mirdeep2_0_0_8/src/indexes/Rfam_index

There is no option right now to specify where the index shall be located.

You could also change the path to it which is located in make_html.pl starting at line
3627. But I would go for the first option.
Best

**Comment by Jammcgro123** [comment]
@Drmirdeep Hi, thanks for your quick response, in terms of the first solution can you explain that to me. Sorry this is the first time im using this and im just getting to terms with mirdeep.

Thanks,
James

**Comment by mschilli87** [comment]
Regarding the 2nd solution: Here is the coded part mentioned by @Drmirdeep: https://github.com/rajewsky-lab/mirdeep2/blob/562963670200e6e63ff7d55c8e99acf4d6184c5b/src/make_html.pl#L3627-L3637

Modifying the definition of the `{script}` variable just before that might also work:
https://github.com/rajewsky-lab/mirdeep2/blob/562963670200e6e63ff7d55c8e99acf4d6184c5b/src/make_html.pl#L3619-L3621

---

Concerning the first idea:

You must have installed mirdeep2 with root permissions, so just run copy paste
the command that failed for the non-privileged user into a terminal with root
permissions:

```sh
bowtie-build --wrapper basic-0 /opt/apps/mirdeep2_0_0_8/src//../Rfam_for_miRDeep.fa /opt/apps/mirdeep2_0_0_8/src/indexes/Rfam_index
```

Then, the index will be build and future non-privileged runs will be able to
read it.


---
@Drmirdeep: Please correct me if I got you wrong.
