### ISSUE TITLE
novel microRNA counts for each sample 

### ISSUE THREAD

**Issue by sridewi1** [rajewsky-lab/mirdeep2#50]
Hi, 

I am wondering if there is any function I can use to extract read counts for each sample from the predicted novel microRNAs from miRDeep2? 

after mapping using the `mapper.pl` and `config.txt ` (list of all samples) as follow:

`mapper.pl config.txt -d -e -h -i -j -l 18 -m -p bowtie_index_mmu -s all_samples.fa -t all_samples.arf`

and followed by `miRDeep2.pl  `

`miRDeep2.pl all_samples.fa mmu_reference.fa all_samples.arf mature_mmu.fa hsa_rno_mature.fa mmu_hairpin.fa -t Mouse` 

 I could only found the read counts for each sample in the `miRNAs_expressed_all_samples.csv` for the known microRNAs but not for the novel microRNAs. Did I miss something here? Thanks in advance for any kind of help!

best, 
Dewi

**Comment by mschilli87** [comment]
maybe helpful: https://github.com/rajewsky-lab/mirdeep2/issues/31

**Comment by sridewi1** [comment]
Dear Marcel,

I think I got it now, how I should proceed to get the novel miRNA counts for each sample.

by following more or less your workflow 
 

>  What I would propose as workflow is the following:
> 
> 1. Predict novel miRNA candidates using miRDeep2.
> 2. Filter down the list (by your own means; could involve validation experiments, random reads as negative controls, ...) to a set your believe are real (and relevant to your biological question).
> 3. Add those novel miRNAs to the known ones (typically obtained from miRbase).
> 4. Quantify all miRNAs using miRDeep2 (treating them equal).
> 5. Perform downstream analyes (DE etc.).

first, I conducted the `miRDeep2.pl` using the mapped `reads.fa` and then using the fasta files in the mirna_results directory (`novel_pres.fa` and `novel_mature.fa`) I conducted the `quantifier.pl `step and got for each sample the novel miRNA counts. 
afterwards, I filtered down these list (using miRDeep score) and another filtering step like minimum read counts and add the remaining novel miRNA to known ones for the DE analysis. 

Thank you so much for your helpful hint.

Best,
Dewi
