### ISSUE TITLE
mirdeep2 quantification questions

### ISSUE THREAD

**Issue by Kennyluo4** [rajewsky-lab/mirdeep2#51]
Hello,
I'm trying to use mirdeep2 for plant miRNA study.  One of the issue I firstly noticed is that the precursor sequence in mature miRNAs detected by miRDeep2 part is different from what I provided (which are downloaded from miRBase), they are normally shorter than miRBase precursors. I suppose it's because of the de novo precursor identification step in mirdeep2.pl module? How to make miRDeep2 stick with provided precursor sequence and do the scoring and quantification?

Plant miRNA is little bit different, so I also tried miRDP2, a modified version for plant miRNA, to identify novel miRNA in my species. Then I only used quantifier.pl module for quantification. But nearly no significant differential expressed miRNA detected by this quantification (done by DESeq2). As plant miRNAs have many families/copys, I believe that not every single miRNA/copy will express at same level. But by quantifier.pl module algorithm, what I can get is similar expression on different mature miRNA family because the sequence similarity. Does miRDeep2 try to tackle this issue? I'm not sure the precursors selection steps in miRDeep2 module can help with this problem. 

Thanks
Ziliang

**Comment by Drmirdeep** [comment]
miRDeep2 is designed for predicting animal miRNAs. Furthermore, there is no differential expression testing included.

**Comment by Kennyluo4** [comment]
Thanks.

**Comment by mschilli87** [comment]
@Kennyluo4:
> How to make miRDeep2 stick with provided precursor sequence and do the scoring and quantification?

For scoring you can't, for quantification you answered your own question:
> Then I only used quantifier.pl module for quantification.

**Comment by Kennyluo4** [comment]
> @Kennyluo4:
> 
> > How to make miRDeep2 stick with provided precursor sequence and do the scoring and quantification?
> 
> For scoring you can't, for quantification you answered your own question:
> 
> > Then I only used quantifier.pl module for quantification.

Thanks for the reply. Simple quantification may have overestimation issue for miRNA families, I just wonder if the quantification in mirdeep2 module can alleviate the problem in animal miRNA if it takes the whole precursor mapping and biogenesis into consideration.
Anyway, I have to deal with what I have.
