### ISSUE TITLE
plant miRNA predict

### ISSUE THREAD

**Issue by huangl07** [rajewsky-lab/mirdeep2#53]
could miRdeep2 used for plant species?

**Comment by mschilli87** [comment]
@huangl07: A [quick search on this issue tracker](https://github.com/rajewsky-lab/mirdeep2/search?q=plant&type=Issues) reveals the following [comment](https://github.com/rajewsky-lab/mirdeep2/issues/51#issuecomment-545590387) from @Drmirdeep:
> miRDeep2 is designed for predicting animal miRNAs.

**Comment by VenithaB** [comment]
Hi! Can you add a warning somewhere saying that miRDeep2 is not designed for plant miRNA?

**Comment by mschilli87** [comment]
I think anybody that read a single review on miRNAs probably knows that they differ between plants and animals so I doubt this is really needed. At least after reading the miRDeep 2 paper it should be clear. People not finding this issue nor #51 would probably also miss that warning.
But you could provide a PR adding this warning to the README or so and see if @Drmirdeep takes it. :wink:

Please keep in mind that this is free software maintained by volunteers. Nobody is payed to keep it around even though somebody might have been payed to write it many years ago.
At this point, as nice it is to see people still use this tool and that it still proves valuable, we can't provide more than bug fixes.
We just don't have the bandwidth to ensure it's easy to use for anyone that doesn't even bother reading the literature. I see software like this as a useful tool provided to me for free, not as a black box that I have a right to do what I want the way I want for me. :wink:

Thank you for understanding and don't misunderstand this as a point directed at you personally:
I'm just trying to help you understand why I'd rather write this lengthy reply than 'just' add this warning. :slightly_smiling_face:
