### ISSUE TITLE
got an error during manual installation of PDF-API2

### ISSUE THREAD

**Issue by HaeWon-chung** [rajewsky-lab/mirdeep2#54]
Hi,

I'm trying to install mirdeep2 and bump into some issues. I'm using Debian version 9.

Initially I tried to install it with install.pl. It worked until it tried to download randfold and failed. So I started to follow manual installation step 9. ranfold was successfully installed but couldn't install PDF-API2. Initially I was trying to install latest version (2.036) of PDF-API2 but failed. Then I download older version (0.73) which was mentioned in the readme file.

Below are the command that I typed and the error message. I typed the command in PDF-API2 folder as instructed.

perl Makefile.PL PREFIX=/home/haewonchung/software/mirdeep2 LIB=/home/haewonchung/software/mirdeep2/lib

Can't locate lib/PDF/API2/Version.pm in @INC (you may need to install the lib::PDF::API2::Version module) (@INC contains: /home/haewonchung/software/mirdeep2/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at Makefile.PL line 42.

It seems like it cannot find version file. The version file is actually in /home/haewonchung/software/mirdeep2/essentials/PDF-API2-0.73/lib/PDF/API2 so I thought the PREFIX should be /home/haewonchung/software/mirdeep2/essentials/PDF-API2-0.73

So I tried this

perl Makefile.PL PREFIX=/home/haewonchung/software/mirdeep2/essentials/PDF-API2-0.73 LIB=/home/haewonchung/software/mirdeep2/essentials/PDF-API2-0.73/lib

But still got exact same error message. It seems like it does not read PREFIX. Could you please help me to install it?

Thanks,

HaeWon

**Comment by HaeWon-chung** [comment]
OK, I googled and figure out the issue by including the directory in INC with -I flag.

So I ran this command and bump into another error message.

perl -I /home/haewonchung/software/mirdeep2/essentials/PDF-API2-0.73 Makefile.PL PREFIX=/home/haewonchung/software/mirdeep2 lib=/home/haewonchung/software/mirdeep2/lib

Checking if your kit is complete...
Looks good
Only one of PREFIX or INSTALL_BASE can be given.  Not both.

**Comment by mschilli87** [comment]
@HaeWon-chung: As your issue seems related to installing PDF-API2, not miRDeep2, did you contact the developers/maintainers of that software? The `install.pl` script just runs `make` for the dependency so it's not really related to anything we'd have control over.
What error did you actually get using `install.pl`? if you get a clean checkout and start over, does it work now?

**Comment by HaeWon-chung** [comment]
I believe this issue is partly due to your instruction to add PREFIX. I changed PREFIX to INSTALL_BASE and solved the issue.

By the way, the error occurred during install.pl seems to be already identified and addressed in miPIE tutorial. Please check step 3 Note: of miPIE tutorial (https://github.com/jrgreen7/miPIE/blob/master/miPIE/Tutorial). I had a same error message.

**Comment by mschilli87** [comment]
@HaeWon-chung: Please note that this toturial refers to miRDeep2 0.0.7 which is over four and a half years old now (see https://github.com/rajewsky-lab/mirdeep2/commit/ef90209adbf93bed9535967e054fcb486fc790ab). Where did you download the code you encountered this issue with?

**Comment by HaeWon-chung** [comment]
I see. I use `git clone https://github.com/rajewsky-lab/mirdeep2.git` to download the code couple of days ago. So I believe I download the most recent one.

**Comment by mschilli87** [comment]
@HaeWon-chung: Thx.

@Drmirdeep: Any idea? Should we fix the manual installation instructions?

**Comment by Drmirdeep** [comment]
The manual instructions are outdated. The install.pl is using INSTALL_BASE. Could you maybe tell us what the screen output was when randfold could not be downloaded/installed?

**Comment by annefleurbrand** [comment]
Hello,

For those having issues installing miRdeep2 with `perl install.pl` and manual installation:

Installing PDF-API2 now
Warning: prerequisite PDF::API2 0 not found.
pdf was/is not installed properly

The other packages are "already installed, nothing to do ..."

The more recent versions of PDF-API2 don't work for me. However, when I install the version that you mention in the manual; PDF-API-0.73 and follow the steps 14-16 it works.

wget (https://www.cpan.org/modules/by-module/PDF/PDF-API2-0.73.tar.gz)

Hope this saves someone else time.

**Comment by jontejj** [comment]
Another cause of this issue could be that PERL5LIB is not set correctly.
```
Error: Perl PDF::API2 package not found
Check if the perl PDF::API2 package is correctly installed and all Pathes were set correctly.
```

export PERL5LIB=mirdeep2/lib/perl5/ worked for me. Where mirdeep2 is the folder where mirdeep2 is located
