### ISSUE TITLE
It didn't generate any output files

### ISSUE THREAD

**Issue by HaeWon-chung** [rajewsky-lab/mirdeep2#55]
Hi,

I finally run mirdeep2 with my data but it doesn't seem to generate any output file. I checked mirdeep_runs folder and there are subfolders but it doesn't contain any output files. There is 1 parameter file and tmp folder. I have attached report log for your review.

[report.log](https://github.com/rajewsky-lab/mirdeep2/files/3799278/report.log)

**Comment by HaeWon-chung** [comment]
I found expression folder which contains html and csv files. But there is single miRNA in miRBase.mrd. Is it what it looks like in general? I'm looking for output.mrd file which I was trying to use for miPIE. But mirdeep2 doesn't seem to generate output.mrd, right?

**Comment by Drmirdeep** [comment]
Did the tutorial run without errors?

**Comment by HaeWon-chung** [comment]
The tutorial runs OK. It generated output files. I'll take a closer look why it failed with my files.

**Comment by mschilli87** [comment]
@HaeWon-chung: Any update on this? If the tutorial works but you pipeline fails, it's likely an error on you side. Still I'd like to make sure before we relaese a new version of miRDeep2. This is the only issue standing between non-git users and [the improvements made to miRDeep2 since February](https://github.com/rajewsky-lab/mirdeep2/compare/v0.1.2...master). :wink:

**Comment by HaeWon-chung** [comment]
I removed and re-installed the software - install.pl works this time. And it seems like working well with my data. It generated csv, html, and output.mrd files. Thanks!

**Comment by mschilli87** [comment]
@HaeWon-chung: Thx for updating us.
@Drmirdeep: Anything holding back a new release now?

**Comment by Drmirdeep** [comment]
This is a bug tracker and not a private messaging service! Please use other channels to reach me. 
And yes, you can do ++ if you like
