### ISSUE TITLE
mapper.pl not recognizing .ebwtl index files produced by bowtie 1.1.1

### ISSUE THREAD

**Issue by VenithaB** [rajewsky-lab/mirdeep2#56]
I used the following command:

```mapper.pl 2_1_I_R1_trimmed.fq -e -h -j -m -p Triticum_aestivum -s mapper.pl_output/2_1_I_R1_trimmed.fa -t mapper.pl_output/2_1_I_R1_trimmed.arf -v -o 8 ```

And got the following output: 

`parsing fastq to fasta format`
`discarding sequences with non-canonical letters`
`discarding short reads`
`collapsing reads`
`mapping reads to genome index`
`Could not locate a Bowtie index corresponding to basename "Triticum_aestivum"`
`Please make sure you used bowtie version 1 to build the index.`
`Usual index files have suffix .ebwt`

`bowtie-build --version` gives:

`bowtie-build version 1.1.1`
`64-bit`
`Built on localhost.localdomain`
`Tue Sep 30 15:42:47 EDT 2014`
`Compiler: gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)`
`Options: -O3 -m64  -Wl,--hash-style=both -DPOPCNT_CAPABILITY`
`Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}`

My index files end with .ebwtl. I used the same command on a smaller genome with index files ending in .ebwt and mapper.pl ran fine. The current genome I'm using is 14.5 billion bp long and accordingly bowtie (which I installed using install.pl) produces .ebwtl files.

**Comment by Drmirdeep** [comment]
fixed

**Comment by VenithaB** [comment]
OK, let me re-install and I'll let you know.

**Comment by mschilli87** [comment]
@Drmirdeep: What do you think? I'd aim for a new release after this and https://github.com/rajewsky-lab/mirdeep2/issues/55.

**Comment by VenithaB** [comment]
Thanks, works fine.
