### ISSUE TITLE
Issue running miRDeep2.pl with .mrd output from quantifier.pl

### ISSUE THREAD

**Issue by plAnneting** [rajewsky-lab/mirdeep2#57]
Hi there and thank you in advance for any insight. I have been running miRDeep2.pl (miRDeep2.0.1.2 Linux-64bit) without any issue until I tried to include the .mrd file from the output of quantifier.pl.

My command was as such:

miRDeep2.pl reads2_collapsed.fa Genome_v2.fasta reads_vs_genome2.arf none related_species_mature.fa related_species_hairpin.fa -q miRBase.mrd -g -1 2>reportlog_quantdeep2.log

I am working in a non-model species with no published miRNA sequences, hence the "none" in the command for known miRNAs.

When I run the same script without the -q miRBase.mrd file everything runs clean and correct output is generated (pdfs, bed file, csv, html, and other files provided in mirdeep_runs/run_<date/time>. However, with the .qrd, the program ran all the way through folding and permutations before hitting a snag at the Rfam portion:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/55992126/68782833-044ece80-0608-11ea-9036-3c045217c3e5.png">

**Error: could not create file expression_analyses/expression_analyses_06_11_2019_t_13_51_31/identified_precursors.fa**

The .bed, .csv, and .html files that were generated are empty, and despite the log reporting that Fasta and bed files have been created in subfolder mirna_results_06_11_2019_t_13_51_31, the directory is completely empty. Also, no pdf directory is generated.

Despite the error occurring, the program still took 156 hours to "finish"! Any idea where the error may have been introduced and how I may go about remedying it?

Thanks greatly.

**Comment by Drmirdeep** [comment]
Hi,
could you paste in here the report.log which is more informative?
I guess it is some file path not found issue. This option was likely never used since it was implemented in the first release of the package. Anyhow. I guess it hangs at the make_html.pl call in the very end of the pipeline so the report.log will be helpful to see.

Apart from that, the runtime scales mainly with the input data and of course the parameters used...
Cheers

**Comment by plAnneting** [comment]
Thank you for your response. Below is the report.log.

[reportlog_quantDeep.log](https://github.com/rajewsky-lab/mirdeep2/files/3843816/reportlog_quantDeep.log)

**Comment by Drmirdeep** [comment]
Seems like when using options -q with mirdeep2.pl then the timestamp must match with the supplied 
mirbase.mrd file. I just added a make directory command to it. 
It should run through now without issues. If you pull the updated package files you can just rerun the last make_html.pl command from your log.
Best

**Comment by plAnneting** [comment]
I downloaded the updated package files and reran from the failed script (make_html.pl), but unfortunately this did not fix the issue and the program is returning the same error.

**Comment by Drmirdeep** [comment]
I don't know why you are running this command within the src directory of the downloaded package. This is not a good idea. The error message says that make_html.pl cannot create the csv file in the current working directory. Please check that you have write permission in your directory you are running the command.

**Comment by Drmirdeep** [comment]
Since there is no updates and this is not really a miRDeep2 issue we close it for now.
