### ISSUE TITLE
mapper.pl and bowtie option

### ISSUE THREAD

**Issue by Juliix** [rajewsky-lab/mirdeep2#59]
Hello, is it possible to modify the bowtie option in the mapper.pl ?

I would like to autorize multi mapping with these options : 

bowtie -q -v 0 -S -a 

Thank you !

**Comment by mschilli87** [comment]
@Juliix: What exactly are you asking for?
Do you want the default behaviour of miRDeep2 to change?
That's not likely to happen for various reasons.

But if you know what to change and where, nobody stops you from changing your local copy of `mapper.pl`. :wink:

**Comment by Juliix** [comment]
Not specially change the default behaviour but to change the options for bowtie.

Mirdeep2 is installed on a server that i use i don't know if i can change the local copy ? and i don't know how to do it ^^

**Comment by mschilli87** [comment]
Changing the options for bowtie would change the behaviour of the whole tool.
You should be able to install anther copy of miRDeep2 in your own home directory of the server: https://github.com/rajewsky-lab/mirdeep2#option-1-with-the-provided-installpl-script.
Then you'd simply run `which mapper.pl` to find the file and moidfy it yourself.
If you run into problems with your changed version, please don't come back for help.
MiRDeep2 is provided as-is and there is no support for additional features.

This tracker is for bugs and as far as I can tell, this is not about a bug in miRDeep2.
