### ISSUE TITLE
fasta format 

### ISSUE THREAD

**Issue by Juliix** [rajewsky-lab/mirdeep2#60]
Hello,

I have an fq file for my reads from my sequencing,

I used mapper.pl to convert the fq file to fasta format 

` mapper.pl ../../Reads/sample1.fq -e -h -i -s sample1.fasta` 

And then i wanted to use the miRdeep2.pl 

`miRDeep2.pl sample1.fasta ../../genome_angers/OBDH_1.0_formated.fasta sample1vsgenome2.arf mature.fa none none -p 2>report.log`
and I have a problem with the identifier 
![image](https://user-images.githubusercontent.com/60847495/74834236-51cf8b80-531b-11ea-9f92-1707458ac9fd.png)

What can i do to fix it ? Is there an option on mapper.pl to fix that ? 

Thank you and have a good day

**Comment by Drmirdeep** [comment]
In general I recommend to check the tutorial and the options that are used there. 
You lack option -m for the mapper which does read collapsing and generates also proper fasta headers for your reads.
