### ISSUE TITLE
replacement of U with T in reference miRNA.fasta

### ISSUE THREAD

**Issue by shannjiang** [rajewsky-lab/mirdeep2#63]
Hi,

I downloaded reference miRNA fasta file from miRBase (http://www.mirbase.org/ftp.shtml) and extracted the miRNAs from the species I want.
I noticed the nucleotide codes in the miRBase fasta file are A, G, C, U.
Should I replace the U with T in case the pop-up of error info because of the inconsistent codes between reference and sample fasta files (U in reference but T in sample)?

thanks,

Shan

**Comment by mschilli87** [comment]
@shannjiang: Have a look at the example files in the tutorial directory.
Also, there is `extract_miRNAs.pl` which you could use.

Finally, if you run miRDeep2 and you get an error that you can't trace down and suspect to be a bug, please share a reproducible example of what you did along with the *whole* log loutput.

**Comment by Drmirdeep** [comment]
miRDeep2 usually handles this. Also see what mschilli87 wrote. I don't see any bug here.
