### ISSUE TITLE
paired-end reads analysis

### ISSUE THREAD

**Issue by sridewi1** [rajewsky-lab/mirdeep2#64]
Hi,

I am wondering if miRDeep2 is able to analyze paired-end reads? I hope I didn't overlooked it in the documentation but so far I didn't see any example for paired-end reads.

Thanks in advance for any kind of help!

cheers,
Dewi

**Comment by mschilli87** [comment]
Why would you sequence a ~20 nt molecule from both ends? What information would the second mate provide that is not already in the first one? Do you have any example for such data or is this a philosphical question?

**Comment by Drmirdeep** [comment]
?

**Comment by mschilli87** [comment]
My best guess is that the samples were multiplexed with longer RNA-seq samples or generated by a facility/company that doesn't offer single-end sequencing (anymore). In this case, both read 2 should be more or less the reverse complement (give or take sequencing errors and different adapter overlaps depending on the sequencing length) of read 1. If that's the case, I would just ignore read 2 and treat the read 1 only data as single-end sRNA-seq library.

**Comment by sridewi1** [comment]
Thank you for your prompt answer. And indeed, we have longer paired-end RNASeq samples from total RNA and try to make the most of our data by including the microRNA analysis.
I was planning to only analyze the read 1 as single-end just as you suggested.  
But I am asking here, just in case I miss something in the documentation for the paired-end option. But now it is clear for me that there is no such case.

Thanks.

**Comment by mschilli87** [comment]
@sridewi1: I wouldn't expect to detect any miRNAs in totalRNA-seq data. Usually during library prep, there is a size selection step that would discard molecules that short. Plus, it's unlikely to actually capture a miRNA with random priming as you'd need a forward and a reverse primer for PCR within a way too short molecule. Also remember that miRNAs make up only a very small fraction of the total RNA. Without knowing the actual project, I can't say much more and further assistance would be out of scope for the miRDeep2 bug tracker, but please don't expect any support from us if you get no/random/unexpected results or even errors running miRDeep2 on totalRNA-seq data.
The best I assume you could do, is to look at pri-/pre-miRNA transcripts. The latter are provided in the mirbase GFF, for the former I'm not aware of any useful annotation. But again, this is unrelated to miRDeep2, a tool to analyze smallRNA-seq data. :wink:
