### ISSUE TITLE
Running quantifier.pl

### ISSUE THREAD

**Issue by anadc71** [rajewsky-lab/mirdeep2#67]
Hi,
I'm not able to run an analysis with the quantifier module, I always get the same error:

Please run the install.pl script first before using the miRDeep2 package
        The install script is located in /home/osboxes/mirdeep2-mas so just do

        cd /home/osboxes/mirdeep2-mas
perl install.pl

         at quantifier.pl line 1442.

I followed all the steps from the tutorial for the installation and everything looks well, I even run the miRDeep2 module without problems, but I'm fighting against quantifier module for almost two weeks and can't find the problem. Any help is welcome.

Thank you,

Ana del Cerro

**Comment by mschilli87** [comment]
Did you follow the steps from the error message?
Clearly something is off with your installation. I'd recommend unstalling miRDeep2, making sure there is no mention of it in your `~/.bashrc` either, downloading the latest version from this github repository and running `perl install.sh`. Then, follow the instructions from that script. So if it tells you to run it again in a new terminal window, do so. Then, run the test data provided with the download and post the full error message incl. every step you did (as text, not screenshot) in a new issue with a title that is specific enough to help future users running ino the same issue to find your issue (and with it the solution) without us having to go through the same issue again for every users that runs into it. If the test data work, but yours don't, feel free to open an issue as well but don't expect much support in that case. :wink:

Closing this as it has no value for the larger community as is and we don't have the bandwidth for individual IT support.
