### ISSUE TITLE
make_html.pl - reading of output.mrd file

### ISSUE THREAD

**Issue by Pfaendner** [rajewsky-lab/mirdeep2#68]
Hi all, 
I have a question, whether the following behavior is intended or faulty:
In the script make_html.pl the output.mrd file is parsed.
Each read is parsed and the content is stored in variable $1, $2, etc.
However, in line 680 these variables are overwritten by the regex 
$hash{$id}{"reads"}{$1}{$counter}{"seq"} =~ /$hash{$id}{"star_seq"}/i
that means that 'known', 'mirbase', 'mirbase-out' can not be set in the following as long as $star_exp_hit equals 0 and will be absent in the final .csv and .html output files.

https://github.com/rajewsky-lab/mirdeep2/blob/b3b0d3bd1d9ab8b5067e307fd1035442a960fa7b/src/make_html.pl#L668-L686

Greets,

Christian Pfaendner

**Comment by Drmirdeep** [comment]
Maybe a bug, maybe not. I would need to do some testing if this was intended 8 years ago. The regex vars are only cleared if the star_exp_hit is still 0. If it is set to 1 then apparently the regex vars are not cleared and stay as they are. So I am not sure this has an effect at all. The only thing that would be affected is the true/false indicator if the predicted mature is the one from the mature input file or not.
