### ISSUE TITLE
fix mirdeep2 wrapper to use modern genome references

### ISSUE THREAD

**Issue by d3d1y** [rajewsky-lab/mirdeep2#7]
It's really unfortunate that mapper.pl will happily map away using a modern reference like hg38, but your new mirdeep2.pl wrapper chokes on the very same reference - complaining about the spaces in the identifiers. 

Please fix mirdeep2 to handle spaces in identifiers so that we don't have to do a bunch of jiggery pokery to fool mirdeep2 into thinking it is working with some kind of ancient reference.

**Comment by mschilli87** [comment]
@d3d1y: Thanks for the feedback.

This could probably be fixed quickly if someone would open a pull request with a fix.
Otherwise it might take a while as it is 'just annoying' but there is a workaround, so priority to fix this will be rather low.

**Comment by d3d1y** [comment]
The work around being maintaining a special, edited version of every reference I need to work with so that miRDeep2 doesn't freak out.

**Comment by d3d1y** [comment]
Here is the very specific check done by miRDeep2.pl to reject references with modern identifiers:
```
    open IN,"<$file_genome";
	$line=<IN>;
	chomp $line;
    if($line !~ />\S+/){
        printErr();
        die "The first line of file $file_genome does not start with '>identifier'
Genome file $file_genome is not a fasta file\n\n";
    }
	if($line =~ /\s/){
		printErr();
        die "Genome file $file_genome has not allowed whitespaces in its first identifier\n\n";
	}

	## get genome ids
	my $tmps=`grep ">" $file_genome`;
my %genomeids = map { $_ => 1 } split("\n",$tmps);
```

**Comment by Drmirdeep** [comment]
We consider it good practice not to use whitespace either in ids nor in file names nor in pathnames!
hg38 is available with non whitespace identifiers from here
http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/
