### ISSUE TITLE
File mirdeep_runs/run_07_09_2020_t_11_03_47/output.mrd is empty

### ISSUE THREAD

**Issue by crikkia** [rajewsky-lab/mirdeep2#71]
Hello,

I run miRDepp2 on a Linux machine. Here there is the command: 
$ miRDeep2.pl ../B.reads_collapsed/all_BV_collapsed_reads2.fa /home/cristina/Genomes/SeMNPV_Genome/SeMNPV_refSeq_genome.fa ../1.mapper_results/all_BV_collapsed_reads2.arf ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_mature.fa ../A.miRNA_baculo_pubblicati/species_cercanas_matureOK.fa ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_prec.fa 2>report.log

Everything is working fine until the miRDeep core algorithm that gave me the following error:

Error:
        File mirdeep_runs/run_07_09_2020_t_11_03_47/output.mrd is empty

Now running miRDeep2_core_algorithm.pl with option -t to see why all precursors were discarded
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 331495.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 374160.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 441425.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 441493.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1445, <FILENAME> line 455940.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1445, <FILENAME> line 505619.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 507901.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 507947.
The debug file is called error.output.mrd_07_09_2020_t_11_03_47

Exiting now

What is it going wrong? What can I do to solve this problem?
Thanks for your help

Cristina

**Comment by Drmirdeep** [comment]
Seems to be an issue with the input files. Please check that none of your files is empty.
You could paste in here the first 10 lines of your all_BV_collapsed_reads2.arf file and you miRNA input files. 

Did the tutorial run fine without issues?

**Comment by crikkia** [comment]
Hi! Thanks for your reply. 
The tutorial works fine as well as some previous analysis. It is now when I am stacked with this issue.
I checked the input files and they are not empty, here below I have pasted the head of all of them (except genome). In the next post I will paste the whole report

Here there are the first ten lines of all_BV_collapsed_reads2.arf

BBV_6603987_x573        19      1       19      tacttcagagctgtcggcc     NC_002169.1     19      123847  123865  tacttcagagctgtcggcc       +       0       mmmmmmmmmmmmmmmmmmm
BBV_6953989_x437        25      1       25      caacgacgtgtctgccaatttgccc       NC_002169.1     25      123820  123844  caacgacgtgtctgccaatttgccc +       0       mmmmmmmmmmmmmmmmmmmmmmmmm
BBV_7131991_x381        21      1       21      gatacttcagagctgtcggcc   NC_002169.1     21      123845  123865  gatacttcagagctgtcggcc     +       0       mmmmmmmmmmmmmmmmmmmmm
BBV_7529687_x282        27      1       27      gtcaacgacgtgtctgccaatttgccc     NC_002169.1     27      123818  123844  gtcaacgacgtgtctgccaatttgccc       +       0       mmmmmmmmmmmmmmmmmmmmmmmmmmm
BBV_7910041_x206        20      1       20      taatggaatcgggcaactcc    NC_002169.1     20      928     947     taatggaatcgggcaactcc      +       0       mmmmmmmmmmmmmmmmmmmm
BBV_7912912_x205        20      1       20      aggcacaggacgatgagaac    NC_002169.1     20      1031    1050    aggcacaggacgatgagaac      -       0       mmmmmmmmmmmmmmmmmmmm
BBV_8112386_x171        18      1       18      aaattagacgctcaggcc      NC_002169.1     18      123866  123883  aaattagacgctcaggcc+       0       mmmmmmmmmmmmmmmmmm
BBV_8115806_x171        18      1       18      gcctctttacaacggacc      NC_002169.1     18      714     731     gcctctttacaacggacc+       0       mmmmmmmmmmmmmmmmmm
BBV_8132251_x169        19      1       19      gtacgtcggcaccaacaac     NC_002169.1     19      480     498     gtacgtcggcaccaacaac       +       0       mmmmmmmmmmmmmmmmmmm
BBV_8230474_x155        28      1       28      catccgcatcgtcgagcccgtgtacgtc    NC_002169.1     28      459     486     catccgcatcgtcgagcccgtgtacgtc      +       0       mmmmmmmmmmmmmmmmmmmmmmmmmmmm

Here there are the first ten lines of all_BV_collapsed_reads2.fa
>BBV_0_x457109
TCTTCGGTAGTATAGTGGTCAGTATCCC
>BBV_457109_x285156
CAGGACCAATCCTTTTTAAAGCT
>BBV_742265_x129428
TACCCTGTAGATCCGAATTTGT
>BBV_871693_x109060
TGGACGGAGAACTGATAAGGGC
>BBV_980753_x95265
CATCACAGTCAGAGTTCTAGCT

Here the first ten lines of my mature miRNAS from my species (obtained from Vir-Mir DB)
>8501-5p
AAUCGGGACCGUGGUGCUCAAAGUCA
>8501-3p
ACGUGAGACGGCACGUUUCGAACGUC
>8502-5p
GCCGUCAUGAGAGCAAUGAUGCGGAC
>8502-3p
CCCAACAUUUCUUAUGACGCUGCGGA
>8503-5p
GGCGGCGUUGGGAGCGCCGUGAUUGC

Here the first ten lines of precursors

>8482
UGUCGUCGUCGUCGUCAGUGUCAGUGUCGGUGUCGGuaucgucaucguccUCGAUAUCGAUCGGAGGCUCACGAGGAGUUUCGACG
>8481
AAGGUGGUGGGUCAAGAGUCGUGUCUCGACGGcacgcucgacuauuacucgcccgaaaaaUUAGCGGGACGACGAUACGACUACCAUUUU
>8483
UAUUGCCGCCGACGUCGAUGCCCCUGCCGACGUCGAUGcuucugccgaCGUCGAUGCCGAUGUCGACAUCGAUGCCGAUGCCGAUG
>8487
ACGCAAUCAAAACUCUAGUACUCGAUCUUUGCUUUCGUCcaagaucuucGACGAAAGCAAAGAUCAUGUACUAGAGUUUUUAAGUAGUGU
>8484
UACAAAACUCUAGUACUCGAUCUUUGCUUUCGUCcaagaucuucGACGAAAGCAAAGAUCAUGUACUAAAAUUUAUUA

Here the first ten lines of matures miRNA from closely related species

>AcMNPV-miR-1
GCGACGACUCGGUUAAGGAA
>bmnpv-miR-3
GAAAGCCAAACGAGGGCAGGCG
>bmnpv-miR-1
AAAUGGGCGGCGUACAGCUGG
>bmnpv-miR-2
GGGGUUUUUGUACGGCGGCCC
>bmnpv-miR-4
GGUGGAUGUGAUUGUUGACGACA

**Comment by crikkia** [comment]
Here there is the whole report log

#Starting miRDeep2
/usr/local/programas/mirdeep2-master/bin/miRDeep2.pl ../B.reads_collapsed/all_BV_collapsed_reads2.fa /home/cristina/Genomes/SeMNPV_Genome/SeMNPV_refSeq_genome.fa ../1.mapper_results/all_BV_collapsed_reads2.arf ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_mature.fa ../A.miRNA_baculo_pubblicati/species_cercanas_matureOK.fa ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_prec.fa

miRDeep2 started at 10:12:56


mkdir mirdeep_runs/run_22_10_2020_t_10_12_56

#testing input files
started: 10:12:56
sanity_check_mature_ref.pl ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_mature.fa


ended: 10:12:56
total:0h:0m:0s

started: 10:12:56
sanity_check_mature_ref.pl ../A.miRNA_baculo_pubblicati/species_cercanas_matureOK.fa


ended: 10:12:56
total:0h:0m:0s

sanity_check_reads_ready_file.pl ../B.reads_collapsed/all_BV_collapsed_reads2.fa

started: 10:12:56

ended: 10:13:06
total:0h:0m:10s

started: 10:13:06
sanity_check_genome.pl /home/cristina/Genomes/SeMNPV_Genome/SeMNPV_refSeq_genome.fa


ended: 10:13:06
total:0h:0m:0s

started: 10:13:06
sanity_check_mapping_file.pl ../1.mapper_results/all_BV_collapsed_reads2.arf


ended: 10:13:07
total:0h:0m:1s

started: 10:13:07
sanity_check_mature_ref.pl ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_prec.fa


ended: 10:13:07
total:0h:0m:0s

started: 10:13:07
Quantitation of expressed miRNAs in data


quantifier.pl -p ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_prec.fa -m ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_mature.fa  -r ../B.reads_collapsed/all_BV_collapsed_reads2.fa   -y 22_10_2020_t_10_12_56 -k
getting samples and corresponding read numbers

Converting input files
building bowtie index
mapping mature sequences against index
mapping read sequences against index
Mapping statistics

#desc   total   mapped  unmapped        %mapped %unmapped
total: 23815038 33851   23781187        0.142   99.858
BBV: 12070796   6884    12063912        0.057   99.943
HBV: 11744242   26967   11717275        0.230   99.770
analyzing data
Expressed miRNAs are written to expression_analyses/expression_analyses_22_10_2020_t_10_12_56/miRNA_expressed.csv
    not expressed miRNAs are written to expression_analyses/expression_analyses_22_10_2020_t_10_12_56/miRNA_not_expressed.csv

Creating miRBase.mrd file

make_html2.pl -q expression_analyses/expression_analyses_22_10_2020_t_10_12_56/miRBase.mrd -k Sexi_Vir-Mir_mature.fa -y 22_10_2020_t_10_12_56  -o -i expression_analyses/expression_analyses_22_10_2020_t_10_12_56/Sexi_Vir-Mir_mature.fa_mapped.arf    -M miRNAs_expressed_all_samples_22_10_2020_t_10_12_56.csv
miRNAs_expressed_all_samples_22_10_2020_t_10_12_56.csv file with miRNA expression values
parsing miRBase.mrd file finished
creating PDF files
creating pdf for 8495 finished
creating pdf for 8575 finished
creating pdf for 8507 finished
creating pdf for 8569 finished
creating pdf for 8511 finished
creating pdf for 8565 finished
creating pdf for 8521 finished
creating pdf for 8566 finished
creating pdf for 8496 finished
creating pdf for 8483 finished
creating pdf for 8541 finished
creating pdf for 8554 finished
creating pdf for 8563 finished
creating pdf for 8499 finished
creating pdf for 8501 finished
creating pdf for 8553 finished
creating pdf for 8550 finished
creating pdf for 8497 finished
creating pdf for 8491 finished
creating pdf for 8573 finished
creating pdf for 8537 finished
creating pdf for 8530 finished
creating pdf for 8543 finished
creating pdf for 8492 finished
creating pdf for 8508 finished
creating pdf for 8513 finished
creating pdf for 8525 finished
creating pdf for 8546 finished
creating pdf for 8571 finished
creating pdf for 8516 finished
creating pdf for 8505 finished
creating pdf for 8555 finished
creating pdf for 8556 finished
creating pdf for 8576 finished
creating pdf for 8562 finished
creating pdf for 8567 finished
creating pdf for 8564 finished
creating pdf for 8498 finished
creating pdf for 8536 finished
creating pdf for 8538 finished
creating pdf for 8494 finished
creating pdf for 8535 finished
creating pdf for 8487 finished
creating pdf for 8529 finished
creating pdf for 8572 finished
creating pdf for 8519 finished
creating pdf for 8510 finished
creating pdf for 8500 finished
creating pdf for 8545 finished
creating pdf for 8526 finished
creating pdf for 8531 finished
creating pdf for 8547 finished
creating pdf for 8517 finished
creating pdf for 8558 finished
creating pdf for 8549 finished
creating pdf for 8509 finished
creating pdf for 8515 finished
creating pdf for 8514 finished
creating pdf for 8481 finished
creating pdf for 8490 finished
creating pdf for 8484 finished
creating pdf for 8524 finished
creating pdf for 8534 finished
creating pdf for 8485 finished
creating pdf for 8570 finished
creating pdf for 8542 finished
creating pdf for 8503 finished
creating pdf for 8574 finished
creating pdf for 8522 finished
creating pdf for 8539 finished
creating pdf for 8559 finished
creating pdf for 8533 finished
creating pdf for 8523 finished
creating pdf for 8493 finished
creating pdf for 8486 finished
creating pdf for 8504 finished
creating pdf for 8512 finished
creating pdf for 8532 finished
creating pdf for 8482 finished
creating pdf for 8527 finished
creating pdf for 8540 finished
creating pdf for 8506 finished
creating pdf for 8488 finished
creating pdf for 8548 finished
creating pdf for 8568 finished
creating pdf for 8557 finished
creating pdf for 8552 finished
creating pdf for 8560 finished
creating pdf for 8528 finished
creating pdf for 8561 finished
creating pdf for 8520 finished
creating pdf for 8518 finished
creating pdf for 8489 finished
creating pdf for 8502 finished
creating pdf for 8551 finished
creating pdf for 8544 finished

ended: 10:14:39
total:0h:1m:32s

started: 10:14:39
rna2dna.pl ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_mature.fa > mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/Sexi_Vir-Mir_mature.fa

rna2dna.pl ../A.miRNA_baculo_pubblicati/species_cercanas_matureOK.fa > mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/species_cercanas_matureOK.fa


ended: 10:14:39
total:0h:0m:0s

rna2dna.pl ../A.miRNA_baculo_pubblicati/Sexi_Vir-Mir_prec.fa > mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/Sexi_Vir-Mir_prec.fa


ended: 10:14:39
total:0h:0m:0s

#parsing genome mappings
parse_mappings.pl ../1.mapper_results/all_BV_collapsed_reads2.arf -a 0 -b 18 -c 25 -i 5 > mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/all_BV_collapsed_reads2.arf_parsed.arf

started: 10:14:39

ended: 10:14:43
total:0h:0m:4s

#excising precursors
started: 10:14:43
excise_precursors_iterative_final.pl /home/cristina/Genomes/SeMNPV_Genome/SeMNPV_refSeq_genome.fa mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/all_BV_collapsed_reads2.arf_parsed.arf mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.fa mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.coords 50000
1       3556

ended: 10:15:09
total:0h:0m:26s

#preparing signature
prepare_signature.pl ../B.reads_collapsed/all_BV_collapsed_reads2.fa mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.fa 1 -a mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/Sexi_Vir-Mir_mature.fa -o mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/signature.arf 2>>error_22_10_2020_t_10_12_56.log

started: 10:15:09

ended: 10:15:21
total:0h:0m:12s

#folding precursors
started: 10:15:21
RNAfold < mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.fa -noPS > mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.str


ended: 10:15:42
total:0h:0m:21s

#computing randfold p-values
select_for_randfold.pl mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/signature.arf mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.str > mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors_for_randfold.ids

started: 10:15:42

ended: 10:15:46
total:0h:0m:4s

started: 10:15:46
fastaselect.pl mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.fa mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors_for_randfold.ids > mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors_for_randfold.fa


ended: 10:15:46
total:0h:0m:0s

started: 10:15:46
randfold -s mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors_for_randfold.fa 99 > mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors_for_r
ended: 10:19:
ended: 10:24:06
total:0h:8m:20s

#running miRDeep core algorithm
started: 10:24:07
miRDeep2_core_algorithm.pl mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/signature.arf mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.str -s mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/species_cercanas_matureOK.fa -v -50 -l 18 -y mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors_for_randfold.rand > mirdeep_runs/run_22_10_2020_t_10_12_56/output.mrd

ended: 10:24:11
total:0h:0m:4s

Error:
        File mirdeep_runs/run_22_10_2020_t_10_12_56/output.mrd is empty

Now running miRDeep2_core_algorithm.pl with option -t to see why all precursors were discarded
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 331495.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 374160.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 441425.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 441493.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1445, <FILENAME> line 455940.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 494384.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1445, <FILENAME> line 505619.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 507901.
Negative repeat count does nothing at /usr/local/programas/mirdeep2-master/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 507947.
The debug file is called error.output.mrd_22_10_2020_t_10_12_56

Exiting now

**Comment by crikkia** [comment]
Last comment: If I run mirDeep2 without mature and precursor miRNAs from my and close related species (/usr/local/programas/mirdeep2-master/bin/miRDeep2.pl ../B.reads_collapsed/all_BV_collapsed_reads2.fa /home/cristina/Genomes/SeMNPV_Genome/SeMNPV_refSeq_genome.fa ../1.mapper_results/all_BV_collapsed_reads2.arf none none none) I still have the same error. So the error should be in the arf or in the read file.
Thanks for any hints!
Best
Cris

**Comment by Drmirdeep** [comment]
Since the core algorithm ran only 4 seconds I would first check if none of the input files is empty.

mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/signature.arf mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors.str mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/species_cercanas_matureOK.fa 
mirdeep_runs/run_22_10_2020_t_10_12_56/tmp/precursors_for_randfold.rand

**Comment by Drmirdeep** [comment]
I am closing the thread now since either the problem got solved (if yes please add your solution here) or there is no interest in solving it anymore. You can reopen the thread if you have any news on it.
