### ISSUE TITLE
GNU parallel

### ISSUE THREAD

**Issue by leorippel** [rajewsky-lab/mirdeep2#73]
Hi, I've been trying to use GNU parallel to run miRDeep2.pl uncessfully.

I tried a lot of different setups but none worked.

 `cat /raid/projects/scratch/BioTrans/PinusRadiata/sRNA/mirDeep2020/PiRa_reads_no_short.fa | parallel --dryrun  -j2 --recstart ">" "/home/lrippel/bin/mirdeep2-master/bin/miRDeep2.pl /raid/projects/scratch/BioTrans/PinusRadiata/sRNA/mirDeep2020/PiRa_reads_no_short.fa <(cat)  ../GenomeIdex/PiRa_vs_Genomes.arf none ../GenomeIdex/pabMAture.fa none -g -1"`

Will GNU parallel  work on miRDeep2.pl algorithm?

Can someone help me with the command line?

Cheers.

**Comment by Drmirdeep** [comment]
Not a bug.
