### ISSUE TITLE
ARF output error

### ISSUE THREAD

**Issue by Yatzutzu** [rajewsky-lab/mirdeep2#74]
I tried to use the arf file as input for mirdeep2.pl but it's recognized as not in arf format. Does anyone know how to deal with it? Many thanks!

**Comment by Drmirdeep** [comment]
If it is not recognized than it is not in arf format. Please post the first 10 lines here (e.g. head YOURarfile.arf) and show the command you are running to produce the arf file as well as the command for running miRDeep2.pl.
