### ISSUE TITLE
sanity_check_mature_ref.pl  Error: problem with hairpin.fa

### ISSUE THREAD

**Issue by sdjebali** [rajewsky-lab/mirdeep2#75]
Dear all,

I am using the small rnaseq pipeline from nf-core (https://github.com/nf-core/smrnaseq/), development version, and I have an error from miRDeeep2.

More precisely the error is at the sanity_check_mature_ref.pl  step which says my hairpin.fa file contains unexpected nucleotides (and it seems to indeed include Y characters, see below).

This is run on sus scrofa version 11.1 and with hairpin and mature mirnas from current mirbase.

As I do not imagine changing the mirbase files, I was wondering if something could be done to allow for those nucleotides ?

I am posting the end of the log file below

Best,
Sarah Djebali

```
#Starting miRDeep2
/opt/conda/envs/nf-core-smrnaseq-1.1dev/bin/miRDeep2.pl Susscrofa_FR17MAG201410886_Liver_smallRNA_trimmed_collapsed.fa sus_scrofa_nowhitespace.fa Susscrofa_FR17MAG201
410886_Liver_smallRNA_trimmed_reads_vs_refdb.arf mature.fa none hairpin.fa -d -z _Susscrofa_FR17MAG201410886_Liver_smallRNA_trimmed_collapsed

miRDeep2 started at 16:46:51


mkdir mirdeep_runs/run_22_12_2020_t_16_46_51_Susscrofa_FR17MAG201410886_Liver_smallRNA_trimmed_collapsed

#Starting miRDeep2
#testing input files
started: 16:46:57
sanity_check_mature_ref.pl mature.fa

#testing input files

ended: 16:46:57
total:0h:0m:0s

sanity_check_reads_ready_file.pl Susscrofa_FR17MAG201410886_Liver_smallRNA_trimmed_collapsed.fa

started: 16:46:57

ended: 16:47:06
total:0h:0m:9s

started: 16:47:06
sanity_check_genome.pl sus_scrofa_nowhitespace.fa


ended: 16:48:03
total:0h:0m:57s

started: 16:48:03
sanity_check_mapping_file.pl Susscrofa_FR17MAG201410886_Liver_smallRNA_trimmed_reads_vs_refdb.arf


ended: 16:48:04
total:0h:0m:1s

started: 16:48:04
sanity_check_mature_ref.pl hairpin.fa
  Error: problem with hairpin.fa
  Error in line 4.371: The sequence
  
  UUGUGUGCGUGCCUGGCUCCCUGUAUGCCACACAUGUAGCGCCCAACCCAGAUGYUAAGG
  
  
  contains characters others than [acgtunACGTUN]
  
  Please check your file for the following issues:
  
  I.  Sequences are allowed only to comprise characters [ACGTNacgtn].
  II. Identifiers are not allowed to have withespaces.

```

**Comment by Drmirdeep** [comment]
Hi Sarah,

The code is not going to be changed. 
I can only recommend to change your input sequences. Maybe replace Y by N or whatever Y is supposed to be. 
e.g.
perl -ane 's/y/N/ig;print;' hairpin.fa > hairpin_yn.fa

However,  if your genome also contains non-canonical letters you would have to do it there too. I am not sure if bowtie would allow these. 

Best,
Sebastian
