### ISSUE TITLE
quantifier.pl showing different count for same miRNA

### ISSUE THREAD

**Issue by milag6** [rajewsky-lab/mirdeep2#76]
Hi
I am using mirdeep2 to predict and quantify miRNAs in coral
I am using the quantifier.pl (default parameters)

I ran the mapper then used quantifier this way: 
```
mkdir quantifier_AD_2021
cp mirdeep_runs/run_23_02_2021_t_10_00_00/identified_precursors.fa quantifier_AD_2021/
cp mirna_results_23_02_2021_t_10_00_00/novel_mature_23_02_2021_t_10_00_00_score-50_to_na.fa quantifier_AD_2021/
cp reads6.fa quantifier_AD_2021/
cd quantifier_AD_2021/

quantifier.pl -p identified_precursors.fa -m novel_mature_23_02_2021_t_10_00_00_score-50_to_na.fa  -r reads6.fa  
```

In my results, the precursors have strange suffix such as M:name_of gene, L:name_of gene S::name_of gene
Some miRNAs with the same name AND precursor show multiple times, with different counts
What is the reason for that?
Thanks 
![image](https://user-images.githubusercontent.com/10827806/110054416-c6e6f500-7da6-11eb-9323-62ab33acc259.png)

**Comment by Drmirdeep** [comment]
Please adjust your precursor IDRs. Have a look how precursor IDs from mirbase look like and try to follow this pattern.
