### ISSUE TITLE
mirdeep2 for miRNA detection in giardia

### ISSUE THREAD

**Issue by bendovi** [rajewsky-lab/mirdeep2#8]
Hi,
In Giardia, miRNA length peak is reportedly 26 nt (PMID: 24586143) (compared to 22 nt e.g. in vertebrates).
Will this hamper the sensitivity of mirdeep2 in identifying miRNA in this species?
thanks,
iddo

**Comment by mschilli87** [comment]
Judging by a quick look at the code, I guess the answer to your question is yes:

**Comment by Drmirdeep** [comment]
if you change the line to 29 or a reasonable maximum it may likely work

**Comment by bendovi** [comment]
thanks, great help
