### ISSUE TITLE
MiRBase input files not recognised by mirdeep2.pl

### ISSUE THREAD

**Issue by annefleurbrand** [rajewsky-lab/mirdeep2#80]
Hello,

I installed miRdeep2 as per the instructions on this platform and the mapper.pl and quantifier.pl functions work perfectly. However, when running mirdeep.pl, my MiRBase input files do not seem to be recognised and I get the following error: 

Error: no file containing miRNAs precursors of investigating species specified

Either specify a valid fasta file or say none

**********
The first three arguments to miRDeep2.pl must be files while arguments 4-6 can be files or must be designated as 'none'. Examples:

miRDeep2.pl reads.fa genome.fa reads_vs_genome.arf mautre_ref_miRNAs.fa mature_other_miRNAs.fa  hairpin_ref_miRNAs

or

miRDeep2.pl reads.fa genome.fa reads_vs_genome.arf none none none

Please check if the supplied files exist and the command call to miRDeep2.pl is correct

My code:

```
/home2/fleur/mirdeep2/bin/miRDeep2.pl /home2/fleur/Mapping/BIRDS_pool_processed.fa \
/home2/fleur/Genomes/new_Chicken.fa /home2/fleur/Genomes/BIRDS_pool_mapped_Chicken.arf \
/home2/fleur/MiRBase/gga_matureMiRNA.fa /home2/fleur/MiRBase/gga_hairpinMiRNA.fa -t gga -z .initialPred  \
> miRdeep2.log 2> miRdeep2.err &
```

It does run when I remove the miRBase .fa files or when I replace them with none.

I tried the code with -P and without -P and different approaches for miRBase data preprocessing:

1. 

```
extract_miRNAs.pl /home2/fleur/MiRBase/mature.fa apl,cli,gga,tgu > mature_birds.fa
extract_miRNAs.pl /home2/fleur/MiRBase/hairpin.fa apl,cli,gga,tgu > hairpin_birds.fa
```
2.

# Download mirBase mature and precursor sequences
```
wget ftp://mirbase.org/pub/mirbase/CURRENT/hairpin.fa.gz
wget ftp://mirbase.org/pub/mirbase/CURRENT/mature.fa.gz
```

# Remove white space
```
zcat hairpin.fa.gz | cut -f1 -d" ">/home2/fleur/MiRBase//hairpin_noSpace.fa
zcat mature.fa.gz | cut -f1 -d" " >/home2/fleur/MiRBase//mature_noSpace.fa
```

# Remove non-canonical nucleotides and convert to SL |
```
fastaparse.pl /home2/fleur/MiRBase//hairpin_noSpace.fa -b | fasta_formatter -w 0  >hairpin_cleaned.fa
fastaparse.pl /home2/fleur/MiRBase//mature_noSpace.fa -b | fasta_formatter -w 0 >mature_cleaned.fa
```

# Select chicken miRNAs ..
```
grep -A1 "gga" mature_cleaned.fa  | grep -v -- "^--$" >gga_matureMiRNA.fa
grep -A1 "gga" hairpin_cleaned.fa | grep -v -- "^--$" >gga_hairpinMiRNA.fa
```

I'm sorry if I'm overlooking something very basic... Thank you in advance for any help you can provide!

**Comment by annefleurbrand** [comment]
Apologies, I just worked it out... 

```
/home2/fleur/mirdeep2/bin/miRDeep2.pl /home2/fleur/Mapping/BIRDS_pool_processed.fa /home2/fleur/Genomes/new_Chicken.fa \
/home2/fleur/Genomes/BIRDS_pool_mapped_Chicken.arf /home2/fleur/MiRBase/gga_matureMiRNA.fa none /home2/fleur/MiRBase/hairpin_birds.fa -t gga -z .initialPred
```

**Comment by Drmirdeep** [comment]
Great. Now it would be kind if you let other people know what the exact issue was and what you did to solve it.

**Comment by annefleurbrand** [comment]
> Great. Now it would be kind if you let other people know what the exact issue was and what you did to solve it.

I came across various examples where only two fasta files with known miRNAs where specified in the input without adding "none" for the missing third, so I thought my original code would work.
