### ISSUE TITLE
parameter 

### ISSUE THREAD

**Issue by WeiXu63** [rajewsky-lab/mirdeep2#83]
Hello Drmirdeep,

Sorry for the unclear question. I want to use mirdeep2 to analyze my plant small RNAseq data. According to the literatures I found, I learned the default parameters of mirdeep2 is good for animal small RNAseq data; for plant small RNAseq data, I need to adjust some parameters, i.e. some authors, adjusted the sRNA<=15 hits, and 250nt flanking sequences (on each side on the genome) for plant miRNA analysis. Let's me just quote the original sentence from their manuscript "miRNA Identification. The unannotated reads containing miRNAs were processed for miRNA identification by miRDeep2 v 2.0.0.531 with modified parameters (sRNAs ≤ 15 hits; 250 nt flanking sequences) for plant miRNA characters30. In brief, the analysis procedure of miRDeep2 were: (1) The unannotated reads were aligned to the Jatropha genome sequences using Bowtie v 0.12.9 with perfect matches, and only sRNAs with no more than 15 hits were kept and their flanking sequences (250 nt on each side) on the genome were extracted as candidate miRNA precursors, to satisfy the parameters of miRNAs in plant species as described."

When I use mirdeep2 to analyze my data, I used mapper.pl to align my samples reads to the genome, but I found -r parameter can be used to adjust the hits, but I didn't find a parameter to adjust the flanking sequences. Could you let me know which parameter it is? This is my question. Thanks.
Xu

**Comment by Drmirdeep** [comment]
Hi Xu,

mirdeep(2) was not designed for plant species. However, it exists a mirdeep clone/adaptation for plants which is not from us. Just have a look at some web search machine.

Cheers

**Comment by mschilli87** [comment]
Also, to me this sounds more like an issue with the method section of the paper you quote, if anything.
Why don't you contact the authors and ask them to clarify which parameter they used or in what way they modified the miRDeep2 source code to achieve what they did?

**Comment by WeiXu63** [comment]
> Also, to me this sounds more like an issue with the method section of the paper you quote, if anything.
> Why don't you contact the authors and ask them to clarify which parameter they used or in what way they modified the miRDeep2 source code to achieve what they did?

Thank you for your suggestion. I contacted the authors a week ago and asked them about the modification, but they haven't replied me yet.

**Comment by WeiXu63** [comment]
> Hi Xu,
> 
> mirdeep(2) was not designed for plant species. However, it exists a mirdeep clone/adaptation for plants which is not from us. Just have a look at some web search machine.
> 
> Cheers

You mean miRDeep-P2? Okay, thanks for letting me know. I will give a try. I saw several published literatures used your mirdeep, however, I did learned mirdeep is not designed for plant small RNAseq data analysis. It's a little strange to me. Anyways, thanks for letting me know.

**Comment by Drmirdeep** [comment]
We are not responsible for web search machine entries nor is it in our control if people use the same name and add some characters although these tools use part of our scripts. Unfortunately, we don't have a copyright on the specific letter combination 'm' 'i' 'r' 'd' 'e' 'e' 'p'.
