### ISSUE TITLE
.arf file is empty and miRDeep2.pl is throwing error as reads_collapsed_vs_genomeIIYL1.arf is not in arf format

### ISSUE THREAD

**Issue by harshraj1919** [rajewsky-lab/mirdeep2#84]
Hello, 
I am using miRDeep2 for known and novel miRNA prediction. I was able to predict the known miRNAs but while running the script for novel miRNA prediction it is throwing error as .arf file especially `reads_collapsed_vs_genomeIIYL1.arf` is not in arf format. Can you please help me to solve this issue..

Following is my UNIX command lines. `IIY_L1` is my sample name and I am working on *Vitis vinifera*.

Thanks
Raj

```sh
cd ~/Desktop/smallRNAdata/raw_data/IIY_L1
miRDeep2.pl \
    reads_collapsedIIYL1.fa \
    genome.fa \
    reads_collapsed_vs_genomeIIYL1.arf \
    vvimature.fa \
    none \
    vvistemloop.fa
```

```
#####################################
#                                   #
# miRDeep2.0.1.2                    #
#                                   #
# last change: 22/01/2019           #
#                                   #
#####################################

miRDeep2 started at 15:33:09


#Starting miRDeep2
#Starting miRDeep2
/home/harshraj/SmallRNAseqdata/mirdeep2/bin/miRDeep2.pl reads_collapsedIIYL1.fa genome.fa reads_collapsed_vs_genomeIIYL1.arf vvimature.fa none vvistemloop.fa

miRDeep2 started at 15:33:09


mkdir mirdeep_runs/run_08_09_2021_t_15_33_09

Use of uninitialized value in pattern match (m//) at /home/harshraj/SmallRNAseqdata/mirdeep2/bin/miRDeep2.pl line 354, <IN> line 1.
Use of uninitialized value in pattern match (m//) at /home/harshraj/SmallRNAseqdata/mirdeep2/bin/miRDeep2.pl line 363.
Error: Mapping file reads_collapsed_vs_genomeIIYL1.arf is not in arf format

Each line of the mapping file must consist of the following fields
readID_wo_whitespaces  length  start  end read_sequence genomicID_wo_whitspaces length  start   end     genomic_sequence  strand  #mismatches editstring
The editstring is optional and must not be contained
The readID must end with _xNumber and is not allowed to contain whitespaces.
The genomeID is not allowed to contain whitespaces.
```

---
***edit (@mschilli87):** formatting*

**Comment by mschilli87** [comment]
* How did you install miRDeep2?
* Note that miRDeep2 was developed for animal miRNAs: Though people have used it for plant analyeses as well, there is no official support for it.
* How does your `reads_collapsed_vs_genomeIIYL1.arf` file look like?

**Comment by Drmirdeep** [comment]
Error message is clear. However, no example line from the arf file given. What kind of advice is now desired? I can only guess your that A) your input files are badly formatted or B) You created the arf file yourself. To exclude format error have a look at the tutorial files and see how IDs etc look there and check if your files are similar. If you created the arf file yourself then redo it by using the mapper.pl

**Comment by mschilli87** [comment]
@harshraj1919: Any update on this? I am aiming for a new release 'soon' and would like to get this fixed before if there even is anything to fix on miRDeep2's side.
