### ISSUE TITLE
Can't locate PDF/API2.pm in @INC

### ISSUE THREAD

**Issue by SimoneFromThePlantLab** [rajewsky-lab/mirdeep2#87]
Hello,

sorry to bother again. I posted an issue yesterday, but I solved it, and I've been able to run miRDeep2. Now my problem is that i cannot procude the results.html file.

After the program ran i get the error: 

`Can't locate PDF/API2.pm in @INC (you may need to install the PDF::API2 module) (@INC contains: /media/sf_shared/mirdeep2/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /media/sf_shared/mirdeep2/bin/make_html.pl line 25.
BEGIN failed--compilation aborted at /media/sf_shared/mirdeep2/bin/make_html.pl line 25.`

What can I do?

Thanks again

**Comment by SimoneFromThePlantLab** [comment]
and together with that I'm missing the `results.csv` file.

Thanks

**Comment by mschilli87** [comment]
[Same questions as yesterday](https://github.com/Drmirdeep/drmirdeep.github.io/issues/5#issuecomment-937657710). ;-)

**Comment by Drmirdeep** [comment]
Can't locate PDF/API2.pm

=> You will need to install the PDF/API2.pm perl module. 

I guess you did not use the included install.pl script to install miRDeep2? Otherwise it would have complaint

How did you install miRDeep2?

**Comment by SimoneFromThePlantLab** [comment]
> Hi, I am having the same issue. I installed mirdeep2 using the conda package earlier today.

First, I have installed miRDeep2 by using git and not conda. 
For the PDF/API2.pm what I did was installing it using conda: 

`conda install -c bioconda perl-pdf-api2`

Then inside the termial I looked for `PDF/API2.pm` using `locate PDF/API2.pm` and I found it in the folder `/home/XXXX/miniconda3/lib/site_perl/5.26.2`

Then what I did was to modfy the script of `make_html.pl` by adding `use lib '/home/simone/miniconda3/lib/site_perl/5.26.2';` at line 23, just above the line `use PDF::API2;`

That fixed the problem and I got my html results file together with the results.csv

Hope this is helpful!

**Comment by mschilli87** [comment]
@jd3234, @SimoneFromThePlantLab: Can you please try out my fix?

```sh
[ -e mirdeep2 ] && mv mirdeep2 mirdeep2.backup && \
    git clone --branch=perl_pdf_api2_install_fix_pdf_api2_xs https://github.com/mschilli87/mirdeep2.git && \
    cd mirdeep2 && \
    perl install.pl
```

Please follow the instructions printed by the install script from there on.

If this fails for you, you can restore the previuous state via

```sh
[ -e mirdeep2 ] && [ -e mirdeep2.backup ] && \
    rm -rf mirdeep2 && mv mirdeep2.backup mirdeep2 && \
    echo 'backup restored!'
```

If it works for you without any hack, you can cleanup the backup of your old checkout with

```sh
[-e mirdeep2 ] && [ -e mirdeep2.backup ] && \
    rm -rf mirdeep2.backup && \
    echo 'backup deleted!'
```

**Comment by jd3234** [comment]
@mschilli87 YAY! `bash run_tut.sh` ran successfully!! 
Thanks for fixing this so quickly!
