### ISSUE TITLE
Empty mapped_arf file 

### ISSUE THREAD

**Issue by hothri** [rajewsky-lab/mirdeep2#9]
Hi, 
I am ending up with the below error while using `mapper.pl` 

```
desc   total   mapped  unmapped        %mapped %unmapped
Use of uninitialized value $count2 in subtraction (-) at /data1/WHRI-GenomeCentre/software/mirdeep2/mirdeep2/bin/mapper.pl line 709.
total: 4162286  Use of uninitialized value $count2 in print at /data1/WHRI-GenomeCentre/software/mirdeep2/mirdeep2/bin/mapper.pl line 709.
        4162286 Use of uninitialized value $count2 in division (/) at /data1/WHRI-GenomeCentre/software/mirdeep2/mirdeep2/bin/mapper.pl line 710.
```

Below are the commands used to run the program 

```sh
mapper.pl ${PROJECTDIR}/config.txt -d -e -i -l 18 -h -j -m -p /data/WHRI-GenomeCentre/Genome/Human/mirdeep/GRCh38 -s processed_reads.fa -t mapped_reads.arf -n -v
```

 I am also attaching the log file. 

[mapper.log_25882_1529404721.txt](https://github.com/rajewsky-lab/mirdeep2/files/2114935/mapper.log_25882_1529404721.txt)

**Comment by mschilli87** [comment]
Those seem to be the offensive lines:
https://github.com/rajewsky-lab/mirdeep2/blob/562963670200e6e63ff7d55c8e99acf4d6184c5b/src/mapper.pl#L709-L710

`$count2` is assigned in https://github.com/rajewsky-lab/mirdeep2/blob/562963670200e6e63ff7d55c8e99acf4d6184c5b/src/mapper.pl#L699-L706

So if the error should only occur if there is no (valid) input.

---
@Drmirdeep: Could this be caught by replacing
https://github.com/rajewsky-lab/mirdeep2/blob/562963670200e6e63ff7d55c8e99acf4d6184c5b/src/mapper.pl#L694
by

```pl
my $count2 = 0;
````
or is this a strict case of 'garbage in - garbage out'?

---
@hothri: Can you confirm that you use the latest version from git and could you provide a *minimal*(**!**) input example to reproduce the issue?

**Comment by Drmirdeep** [comment]
The error will be caught by this but the issue will retain since $count2 is not having a value different from 0 then meaning that nothing was counted as mapped. What does the bowtie.log say?

**Comment by Drmirdeep** [comment]
A minimal example file would help. You can also run the mapper.pl command and supply option -u so you can track which files are produced in between

**Comment by linglingtingfei** [comment]
I have the same problem.  Do you fix the bug now?

**Comment by Drmirdeep** [comment]
Hi,

to debug a problem please make sure that you have installed the latest github version properly.

Then please run the tutorial first and see if there are any errors.

If yes please post them here so we can solve the issue. 

If no errors occur during the tutorial run please post a minimal example and post the exact command lines you used.

Cheers

**Comment by linglingtingfei** [comment]
@Drmirdeep Finally, I know where the problem is. I used the bowtie2 to build the index, It should be bowtie. Now I can run the program successfully.

**Comment by mschilli87** [comment]
duplicate of https://github.com/rajewsky-lab/mirdeep2/issues/3
