### ISSUE TITLE
Mirbase URLs changed, links in output don't work

### ISSUE THREAD

**Issue by Shellfishgene** [rajewsky-lab/mirdeep2#90]
Due to some changes on the Mirbase webserver the links to it in the mirdeep2 html output don't work anymore.
Old link example: `http://www.mirbase.org/cgi-bin/query.pl?terms=dre-miR-204-5p`
Should probably be changed to: `https://www.mirbase.org/textsearch.shtml?q=dre-miR-204-5p`
Maybe other links to mirbase are also affected.

**Comment by mschilli87** [comment]
For future reference: The  commit solving this issue was 8911283184c897ab78e1b0347a7907b4d662d2f8.
