### ISSUE TITLE
Install mirdeep2 for all users

### ISSUE THREAD

**Issue by cweiming** [rajewsky-lab/mirdeep2#93]
Hi 

Is possible to install mirdeep2 with a global environment setting for all users?
I have installed the mirdeep2 and worked fine with my own permission.
However, it didn't allow another user to execute the mirdeep2, e.g., www-data (web service's user).
How can I do?

Thanks!

**Comment by mschilli87** [comment]
AFAIK there is no automatic way to do so.
One simple option wouldbe to make your installation accessible for that and add the directory containing it to that users' `PATH` by copying over the corresponding lines from your `.bashrc` to that user's one.

Alternatively, you should be able to move the installation to a system wide path (e.g. `/usr/local/bin`), adjust the hardcoded paths in all scripts (`find <path-to-mirdeep> -type f -exec grep -l <your user name> "{}" \+`  should tell you which files to look at), and finally add the required lines to your global `/etc/profile` to make sure all executables and libraries are found.

Finally, If it's just about a single user, nothing stops you from running `sudo su <user name>` and installing it again for that user.

If you are concerned about having sevaral installations, you could for sure move the mirdeep directory of your installation to a shared location, adjust the permissions so everyone who needs access has access and simply symlink it back to your home directory.
Now, for every new mirdeep user, install mirdeep again (to get the automatic `.bashrc` modification), delete their installation and symlink the share one to their home directory instead. This would allow any user with write access to the shared installation to update it affecting all users linking to it.

Please note that all of this is untested and not officially supported.
I hope it gives you an idea though how to proceed.

I am going to close this as there is nothing left to do from our side.
But feel free to add another comment if you have further questions.

**Comment by Drmirdeep** [comment]
Your question refers to every software you install and is nothing special about miRDeep2. If you can install it then you can also change permissions or it's location. The rest has to do with YOUR system and how it is administrated. So please ask your sys-admin for further help if the answers from above didn't help.
