### ISSUE TITLE
Incorrect script reference in README

### ISSUE THREAD

**Issue by mschilli87** [rajewsky-lab/mirdeep2#94]
[The quantifier module script reference section](https://github.com/rajewsky-lab/mirdeep2/tree/29a07591b5083b5379988743d8e9b04fac7f7d7b#quantifierpl) of [the current README](https://github.com/rajewsky-lab/mirdeep2/tree/29a07591b5083b5379988743d8e9b04fac7f7d7b#readme) contains [an incorrect list of options](https://github.com/rajewsky-lab/mirdeep2/tree/29a07591b5083b5379988743d8e9b04fac7f7d7b#options-2).
A quick `git blame` revealed that [this seems to be the case for over  ten years already](https://github.com/rajewsky-lab/mirdeep2/blame/2cadf437aa1c45fed5401b65776a5c0971dad918/README#L328-L329).
Maybe we should just update the reference of all scripts to catch additional issues like this before the next release?

**Comment by suryanshsangwan** [comment]
working on it

**Comment by Drmirdeep** [comment]
The quantifier.pl in the Readme is updated. However, since no one ever sent a message I guess no one ever looked into it. 
Also, just calling a script without parameters or -h will show the usage on the screen.

**Comment by mschilli87** [comment]
Should we then remove the documentation from the README and point to `-h` for all scipts instead?
I guess no documentation would be better than wrong documentation. :wink:
