### ISSUE TITLE
excise_precursors_iterative_final.pl error

### ISSUE THREAD

**Issue by Sreeranjini611** [rajewsky-lab/mirdeep2#98]
Dear all,

I have an error from miRDeeep2. While I am running mirdeep2.pl, its showing error with precursor. The error is at the excise_precursors_iterative_final.pl 
![Error](https://user-images.githubusercontent.com/68136936/168743934-aa2b0e53-6121-4c68-8470-7aae580b8e6a.png)
(http://excise_precursors_iterative_final.pl/) step which says no precursors excised. I am posting the error below.

Hoping for a positive response.

Thanks and Regards,
Sreeranjini Babu

**Comment by Drmirdeep** [comment]
Looks like something is wrong with your data. Have a look at the tutorial files and check if the read_collapsed file matches with yours. Eg. Read length around 22 nt and top sequence in the range of 100k.
