### ISSUE TITLE
Consultation on the analysis pipeline for species that do not have mature and precursor miRNA sequences in the miRBase database

### ISSUE THREAD

**Issue by wbc569668815** [rajewsky-lab/mirdeep2#99]
Dear Developer Team:
   I have encountered some problems in the process of analyzing miRNA using mirDeep2 and hope to get your help. Questions are as follows:
    1. The species I am analyzing has reference genomes, but there are no mature miRNA sequences and precursor sequences in miRNAbase. I would like to know how to do the specific process. Do I only need to use the miRDeep2.pl script for new miRNA identification, and the required 3 fasta sequence inputs are "none, mature_ref_other_species.fa, none"? 

   2. When using the mapper.pl script to align the sequencing data to the reference genome, why only 33% of the reads are aligned to the reference genome? The command was"mapper.pl reads.fa -c -j -l 18 -m -p cel_cluster -s reads_collapsed.fa -t reads_collapsed_vs_genome.arf -v" (because it is clean data, there is no connector, so I removed the "-k" parameter). And the reads.fa is 931Mb, while the reads_collapsed.fa is only 53.9Mb. When I used the same sequencing data to align with the reference genome using bowtie software, the alignment rate was over 80%.

Looking forward to hearing from you, I would be very grateful.

**Comment by wbc569668815** [comment]
This is the command I run of question 1 "mirdeep2bed.pl r_c.fa ../../Dgl.chr.genome.fa r_c_vs_genome.arf none ../../../ath_mature_miNRA/ath.mature.fa none -t C.elegans 2>report.log"

**Comment by wbc569668815** [comment]
Dear Sebastian Mackowiak,


   I have read the readme and followed the Script Reference before analyzing. I read all the Example uses, but there is no example similar to my case. 


   I provided the command parameters I used on Github, could you tell me why the error occurs? My sequencing data is 931Mb, while reads_collapsed.fa is only 53.9Mb, and the mapping rate is only 33%.  Is this normal?


Thanks for your reply.


Best wishes.


Bingchao


| |
武炳超
博士研究生
|
|
四川农业大学草业科技学院草业科学系
***@***.***
四川省成都市温江区惠民路211号
611130
College of Grassland Science
Sichuan Agricultural University
Huiming Road 211, Chengdu, Sichuan
611130
E-mail: ***@***.***
|
---- Replied Message ----
| From | Sebastian ***@***.***> |
| Date | 6/16/2022 18:05 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [rajewsky-lab/mirdeep2] Consultation on the analysis pipeline for species that do not have mature and precursor miRNA sequences in the miRBase database (Issue #99) |

Read the papers, read the readme.

**Comment by Drmirdeep** [comment]
Again, we don't do consulting. If this is normal or not depends on your data. QC of the input data is done by the user not us. If the mapping rate is low then you need to check your data. The tool apparently works since otherwise there would be no output. You can check all intermediate files created by the mapper tool. If you find a read that maps with your bowtie mapping but not with the mapping you will likely find the reason why it is not mapping.
